### ISSUE TITLE
Publish javascript so that it can be used from jsfiddle

### ISSUE THREAD

**Issue by udalrich** [RakanNimer/react-google-charts#101]
It would be useful if this was published somewhere public, so that it could be used from jsfiddle.

Or if it is, it would be good to document that.  The only instructions I saw for using it were to do an `npm install`, which I do not think is an option on jsfiddle.

**Comment by RakanNimer** [comment]
Yep need to upload umd build, will do that and get back to you here

**Comment by RakanNimer** [comment]
Done. Example fiddle : https://jsfiddle.net/f8zpr8uc/
