### ISSUE TITLE
Receiving PropTypes validation function warnings

### ISSUE THREAD

**Issue by bansalrachita** [rakannimer/react-google-charts#107]
Version used:
react-google-charts 1.2.2
react v0.14.8

Charts component should render the stack bar chart.
Receiving PropTypes validation function warnings.

render() {

        return (<Chart
                data={this.state.data}
                options={this.state.options}
                width={this.state.width}
                height={this.state.height}
                chartType={this.state.chartType}/>

        );
    }

![image](https://cloud.githubusercontent.com/assets/10090750/22628418/c73da47c-eba1-11e6-884c-c28e27aea265.png)

Please let me know how to fix this.

**Comment by a5his** [comment]
@bansalrachita Since the error says deprecated warning related to PropType. Just give a try with a new version of node, react and react-google-chart.

**Comment by deepfriedbrain** [comment]
Refer to this page: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

I have the latest version of react and react-google-chart and still getting the warning. You'll need to import PropTypes from 'prop-types'.

**Comment by alexfqc** [comment]
I did a pull request to fix this error. New version with prop-types import is coming.

**Comment by rakannimer** [comment]
Fixed in v2.
