### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by OracPrime** [RakanNimer/react-google-charts#110]
There is a problem for those of use trying to use this library: it references scriptjs, which does not have a statement of license.  ScriptJs seem unresponsive to the issue of adding a licence (there are outstanding PRs to achieve this), so if you want licence-concerned users to use this repo, then I think you need an alternative to scriptjs.

**Comment by RakanNimer** [comment]
Hey @OracPrime,

Would you be interested in providing a PR replacing the scriptjs code ?

It's only used in GoogleChartLoader.js 

Happy to merge changes !

Cheers

**Comment by OracPrime** [comment]
I'll take a look

**Comment by OracPrime** [comment]
Hmmm.  I think I've got the changes made, but I'm having trouble building and running all the tests.  First issue is that I have to tell eslint to ignore line endings (standard windows problem: Git translates the ending when you pull to a windows machine, but lint is still checking: I tend to downgrade it to a warning so I can ignore it).  Second (more serious issues) is that when I attempt to reference the code in my test project, the fact that the index.js file is actually a jsx file causes the build to fail.

Not quite sure why it's not a problem when I reference the github version via npm, but when I refer to my local build it fails.  I'm fairly new to this stuff, so any pointers welcome...

**Comment by OracPrime** [comment]
Sorted.  PR submitted

**Comment by RakanNimer** [comment]
Merged and published to npm ! Thanks 👍
