### ISSUE TITLE
Timeline tooltips leaking

### ISSUE THREAD

**Issue by OracPrime** [rakannimer/react-google-charts#113]
react-google-charts 1.4.2
react v15.4.2

**Expected behaviour**
If I hover over a bar in a timeline chart, a tooltip appears.  If something now causes my chart to re-render, I expect the tooltip to either immediately on re-render, or better on timeout/mouse-out to disappear
**Actual behaviour**
Any tooltips that are visible when the component re-renders are never unloaded, and clutter up the screen

Steps to reproduce
Have a timeline chart that re-renders on a timer.

**Comment by hegdeas** [comment]
I am also facing the same issue. Is there a solution for this?

**Comment by deepak-brahmania** [comment]
Facing the same issue.

**Comment by RakanNimer** [comment]
Hey ! 
I'm not currently using this library on production and unfortunately don't have time right now to fix this. 

I'm happy to accept and publish PRs though :) 
If you need help with the code feel free to ask me and/or other contributors like @OracPrime 

Cheers !

**Comment by rakannimer** [comment]
Fixed in 2.0.9

[Example Sandbox with setInterval](https://codesandbox.io/s/30vnnk7zk5)
