### ISSUE TITLE
"module" attribute in package.js broke things?

### ISSUE THREAD

**Issue by dvdplm** [RakanNimer/react-google-charts#115]
Version

Tell us which versions you are using:

react-google-charts 1.5.2
react v15.4.2

Latest version added a `"module": "es/index.js",` in commit https://github.com/RakanNimer/react-google-charts/commit/33d2874c3c40675160851a0ce0961a6b03c6a09b which seems to have broken things. When building with Webpack2 I get `"export 'Chart' was not found in 'react-google-charts'`. I can't find any docs on the "module" attribute, but it seems reasonable that it would force loading `es/index.js`, but I'm unsure why?

**Comment by RakanNimer** [comment]
Hey, 
Thanks for reporting that ! I was experimenting with es exports from node_modules, but I couldn't find a practical way to do it yet. Fixed and published to NPM. 
Cheers !

**Comment by OracPrime** [comment]
This was a bad break - it took our web app down in a very obscure way :(  1.5.3 has fixed it though.

**Comment by RakanNimer** [comment]
@OracPrime I really recommend that you fix the exact version of the package you're using in your prod environment dependencies to avoid something like this breaking your code again ! 

Sorry for the disturbance it caused :) 
Cheers !

**Comment by OracPrime** [comment]
I may have missed the point here, but my understanding is that 1.5.1 had a licensing issue.  I submitted a PR which fixed the licensing issue.  1.5.2 did not just include that fix but an "experimental" fix from yourself?

**Comment by dvdplm** [comment]
> 1.5.2 did not just include that fix

@OracPrime are you sure that it's reasonable to expect releases to contain only one fix? I think not. Sure, this release was buggy but bugs happen to the best of us and this one was fixed very quickly. :)

**Comment by OracPrime** [comment]
Agreed, it did have a very speedy fix.
