### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by Sona-** [rakannimer/react-google-charts#116]
Version 1.4.0

Tell us which versions you are using:

react-google-charts ?.?.?
react v0.?.?
Expected behaviour : try to install npm i -s react-google-charts@1.4.0

Actual behaviour

+-- UNMET PEER DEPENDENCY node-sass@^4.0.0
+-- react-google-charts@1.4.0
| `-- scriptjs@2.5.8
`-- UNMET PEER DEPENDENCY webpack@1.13.1

Steps to reproduce
1.  npm i -s react-google-charts@1.4.0

Link to a git repo that reproduces bug :

**Comment by RakanNimer** [comment]
Please try : npm i -s react-google-charts@1.5.3

**Comment by Sona-** [comment]
I got the same error

**Comment by credli** [comment]
Got the same error today, since I was using node v6.7.0 nvm I ran
`nvm install node --reinstall-packages-from=node`

That bumped me up to v7.7.2 which made `npm i -s react-google-charts@1.5.3` work.

Hope it helps
