### ISSUE TITLE
Update unpkg.com release to latest version

### ISSUE THREAD

**Issue by kennyjwilli** [RakanNimer/react-google-charts#119]
unpkg.com does not have the latest release v1.5.3. 

It would also be useful for you to include the JS build in your released .zip file in the [GitHub releases](https://github.com/RakanNimer/react-google-charts/releases).

**Comment by RakanNimer** [comment]
Thanks for the heads up. You can find the code on master here : https://unpkg.com/react-google-charts@1.5.4-alpha.1/umd/react-google-charts.min.js
