### ISSUE TITLE
.babelrc is missing from git

### ISSUE THREAD

**Issue by mcobzarenco** [RakanNimer/react-google-charts#121]
I tried to build the library locally, but it seems `.babelrc` is missing from git.

Tell us which versions you are using:

react-google-charts master

Expected behaviour
Build the library.

Actual behaviour
Running `npm run build` fails with
```
> mv .babelrc .babelrc.backup && nwb build && mv .babelrc.backup .babelrc

mv: cannot stat '.babelrc': No such file or directory
```

Steps to reproduce
1. clone repo
2. npm install
3. npm run build

**Comment by mcobzarenco** [comment]
Nevermind, it does seem to be there, the problem must have been with `nwb`. Closing

**Comment by RakanNimer** [comment]
Cool, please let me know if you encounter any other problems while working with the code. 

Cheers !
