### ISSUE TITLE
Create multiple chart-types in one combined chart

### ISSUE THREAD

**Issue by Benvorth** [RakanNimer/react-google-charts#122]
Can I print more than one chart-type in one chart? E.g. combine a line-chart and a bar-chart?

**Comment by RakanNimer** [comment]
Hmm, not sure this is possible with the google charts API. You could hack around it ( by removing the grids and superposing the charts for example ) but I'm not sure it would result in maintainable code.

**Comment by Benvorth** [comment]
Found it, it's called a `Combo Chart` :-)

**Comment by RakanNimer** [comment]
Cool ! 
Let me know if it works, and I'll close the issue.

**Comment by Benvorth** [comment]
it works:

![asa](https://cloud.githubusercontent.com/assets/13131335/24203206/5ba3eec8-0f15-11e7-9fbd-268bb902a445.png)

**Comment by Benvorth** [comment]
let chartOptions = {
      hAxis: {title: 'x Axis'},
      vAxis: {title: 'y Axis'},
      legend: 'none',
      seriesType: 'bars',
      series: {'1': {type: 'line', targetAxisIndex: '1'}}
    }

and 

    let chartData= [
         ['t', 'value', 'avg_value'],
         [1, 2345, 2.24],
         ...
    ]
