### ISSUE TITLE
[Error] Area Chart renders but throws Not enough columns error.

### ISSUE THREAD

**Issue by a5his** [RakanNimer/react-google-charts#123]
Version
react-google-charts 1.5.3
react ^15.3.0

Expected behaviour
Render area chart without any error.

Actual behaviour
Throwing error while rendering area chart

Steps to reproduce
1. Provide below sample data 
```
[
    ['CL1', 'CL2, 'CL3', 'CL4', 'CL5'],
    ["String", 100, 100, 100, 10],
    ["String", 1231, 123, 12, 123]
]
``` 
2. Use Chart component
```
<Chart
        chartType="AreaChart"
        data={this.state.data}
        options={this.state.options}
        graph_id="AreaChart"
        width="100%"
        height="400px"
        loader="Loading Chart..."
      />
```
**Error Screenshot**
<img width="1273" alt="screen shot 2017-03-22 at 3 56 49 pm" src="https://cloud.githubusercontent.com/assets/330362/24242078/cae070f8-0fde-11e7-9401-60f14f320169.png">

**Comment by RakanNimer** [comment]
Please check example scatter chart props here : https://github.com/RakanNimer/react-google-charts/blob/master/src/constants/SAMPLE_DATA.js#L115 
and in the examples. 

Going to close this issue, please feel free to re-open if it persists.

**Comment by a5his** [comment]
@RakanNimer 
Just updated the content, this is related to AreaChart. Chart gets rendered but throws an error as well.

**Comment by RakanNimer** [comment]
Thanks for the clarification ! 

If you could provide a link to a repo that reproduces your issue then it would make it easier for me or one of the other contributors to help.

**Comment by a5his** [comment]
This issue is related to google charts.
Thanks.
