### ISSUE TITLE
README

### ISSUE THREAD

**Issue by a5his** [RakanNimer/react-google-charts#126]
Example path should be correct. The path should be `demo` rather. I don't see `example` folder in this codebase.

<img width="908" alt="screen shot 2017-03-23 at 10 56 38 pm" src="https://cloud.githubusercontent.com/assets/330362/24260534/45b8f09c-101c-11e7-8382-dd6f192a56b8.png">

**Comment by RakanNimer** [comment]
Hey, 
Thanks for catching that !
