### ISSUE TITLE
How to allow HTML in ORG chart

### ISSUE THREAD

**Issue by mvenuksai** [rakannimer/react-google-charts#128]
Below are the two fiddle samples one from google chart and other on react google chart:
https://jsfiddle.net/mq2216d3/1/

https://jsfiddle.net/f8zpr8uc/48/

Here there are two issues
1.The root node is not display the text in F field as compared to non react  Google Chart
2. The html's are not getting encoded.

Thansk,
Venu

**Comment by mcolburn** [comment]
You need to set the allowHtml option:

                     options={{allowHtml: true}}

**Comment by rakannimer** [comment]
Example : https://codesandbox.io/s/q3pxx760n9
