### ISSUE TITLE
Responsive Line Chart with fontName throw errors

### ISSUE THREAD

**Issue by jdeslieres** [rakannimer/react-google-charts#129]
Version

react-google-charts 1.5.3
react 15.4.1
react-measure 1.4.6

I have this following Component:

```
'use strict';

import React, {PropTypes} from 'react';
import Measure from 'react-measure';
import {Chart} from 'react-google-charts';

export class LineGraph extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      dimensions: {
        width: -1,
        height: -1
      }
    };
  }

  getOptions() {
    const { width, height } = this.state.dimensions;

    let options = {};
    options.height = height;
    options.width = width;
    options.chartArea = {
      height: (height - 50),
      width: (width - 50)
    };

    options.fontName = 'Open Sans'

    return options;
  }

  render() {
    return (
      <div className="line-graph">
        <Measure onMeasure={(dimensions) => { this.setState({dimensions}); }}>
            <div ref="lineChartContainer" className={"line-chart-container"}>
              <Chart
                chartType="LineChart"
                data={[['Time','A', 'B'], [0,1,3], [1,2,2], [2,3,1]]}
                options={this.getOptions()}
              />
            </div>
        </Measure>
      </div>
    );
  }
}
```

Expected:

- The Line Chart is generated properly.
- The Line Chart is responsive (with react-measure).
- No error is thrown.

Actual:

- The Line Chart is generated properly.
- The Line Chart is responsive (with react-measure).
- An error is thrown:

> Uncaught Error: Not enough columns given to draw the requested chart.
    at gvjs_oI.gvjs_.I$ (jsapi_compiled_ui_module.js:588)
    at gvjs_oI.gvjs_2G (jsapi_compiled_ui_module.js:582)
    at new gvjs_oI (jsapi_compiled_ui_module.js:685)
    at gvjs_PK.gvjs_.tH (jsapi_compiled_ui_module.js:973)
    at gvjs_PK.gvjs_.ro (jsapi_compiled_ui_module.js:980)
    at gvjs_zz (jsapi_compiled_ui_module.js:125)
    at gvjs_Bz (jsapi_compiled_ui_module.js:124)
    at gvjs_PK.<anonymous> (jsapi_compiled_ui_module.js:977)
    at e.YK (jsapi_compiled_default_module.js:41)
    at gvjs_Sl (jsapi_compiled_default_module.js:44)

Notes:
So I have a Line Chart that is shown properly, than is responsive but flood the console with many errors. The errors also make no senses because it says the chart does not have _"enough columns to draw the requested chart"_ but it is drawn correctly.

Further investigation have shown the error can be stopped by:

1) If I remove the fontName from the options, or choose either _Arial_ or _Times New Roman_. (_Open Sans_, _Times_ and _Helvetica_ all throw errors).
2) If I remove the Measure tag from the JSX.

So I was wondering why this error is thrown? 
Also how can I have a responsive Line Chart with _Open Sans_ font?

**Comment by jdeslieres** [comment]
Note that I use react-measure to make this chart responsive..

**Comment by aarchbold** [comment]
I'm experiencing this same issue. Doesn't seem to be related to line chart. We're getting it in PieChart and ComboChart as well.

**Comment by RakanNimer** [comment]
Could you provide a repository with minimum code necessary to reproduce ? Will help us debug this faster !

Cheers

**Comment by rakannimer** [comment]
Does this still happen in v2 ? 

I tried to reproduce unsuccessfully.
