### ISSUE TITLE
Unable to use CandleStick chart

### ISSUE THREAD

**Issue by khennicb** [RakanNimer/react-google-charts#132]
##  Version

react-google-charts@1.5.4-alpha.1
react v15.4.2

## Initial purpose

Display a CandleStick chart.

I stay tune to react if some information are missing.
I would like to use the react-google-chart component in a monitoring application, but i need this CandleStick chart 👍 ! 

## Issue

"Rendering Chart" stay on the screen, the chart is never displayed.
The error found in the browser console is 

`Chart.js:169 Uncaught (in promise) Error: Failed to set DataTable from data props ! `
`    at Chart.buildDataTableFromProps (Chart.js:169)`
`    at Chart.drawChart (Chart.js:213)`
`    at Chart.js:80`

## Code used

[fiddle here](https://jsfiddle.net/pzrc0kv8/)

```
import React, { Component } from 'react';
import { Chart } from 'react-google-charts';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className={'my-pretty-chart-container'}>
        <Chart
          chartType="CandlestickChart"
          data={[
            ['Mon', 20, 28, 38, 45],
            ['Tue', 31, 38, 55, 66],
            ['Wed', 50, 55, 77, 80],
            ['Thu', 77, 77, 66, 50],
            ['Fri', 68, 66, 22, 15]]}
          options={{}}
          graph_id="ScatterChart"
          width="100%"
          height="400px"
          legend_toggle
        />
      </div>
    );
  }
}

export default App;
```

**Comment by khennicb** [comment]
Okay, the data format is not the good one.
```data={[['Mon','Tue','Wed','Thu', 'Fri'],[
            [20, 28, 38, 45],
            [31, 38, 55, 66],
            [50, 55, 77, 80],
            [77, 77, 66, 50],
            [68, 66, 22, 15]]]}```
It gives something.
Can someone is able to show me where i can find the doc about data format ?

**Comment by RakanNimer** [comment]
Sorry for the late reply. You should be able to find all the details you need [here](https://developers.google.com/chart/). 
I'm going to close this, if there's a bug specific to this library please feel free to re-open it.
