### ISSUE TITLE
Improve loading chart message

### ISSUE THREAD

**Issue by alexfqc** [RakanNimer/react-google-charts#133]
Version

Tell us which versions you are using:

react-google-charts 1.5.4-alpha.1
react v15.4.2
Expected behaviour
Custom message / component when charting is loading

Actual behaviour
Static message "Rendering Chart"
Steps to reproduce

Load any Chart

Link to a git repo that reproduces bug :

**Comment by mrhammo** [comment]
You can show a custom message when the chart is loading by setting the `loader` property:

```
<Chart
    chartType="Line"
    data={ [...] }
    loader={ <span className="text-muted">Wait a second, I'm loading...</span> }
/>
```

**Comment by alexfqc** [comment]
Thanks, I can load a custom component either loader={<Loading />}
