### ISSUE TITLE
Tooltips do not disappear when this.setState is called from any chart event callback

### ISSUE THREAD

**Issue by fk-ajain** [RakanNimer/react-google-charts#134]
react-google-charts  v1.5.4-alpha.1
react v15.4.1

Expected behaviour
Tooltips should not stay visible when this.setState is called from any event callback of chart

Actual behaviour
Tooltips never go away if following steps are reproduced

Steps to reproduce
Was issue #51 closed with a fix? I observe something similar with the latest version:
Basically when handling any chart Event, if this.setState is called (essentially render() of chart's container component being called), tooltips do not disappear.

Relevant bits of code to repro:
```
class SomeComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {selected: null};
  }

  render() {
    <Modal some_options={}>
      <Chart
        chartType="Timeline"
        columns={this.timeline.cols}
        rows={this.timeline.rows}
        options={timeline: {showBarLabels: false},tooltip: {isHtml: true}}
        graph_id="TimelineChart"
        width="800px"
        height="400px"
        chartEvents={[{
          eventName: 'select',
          callback: this.handleSelectCallback
        }]}
        chartPackages={['corechart', 'timeline']}
      />
    </Modal>
  }
  
  handleSelectCallback(chart) {
    this.setState({selected: chart.chart.getSelection()[0].row});
  }
}
```

**Comment by davidecarpini** [comment]
from:

https://github.com/RakanNimer/react-google-charts/issues/100#issuecomment-273939149

I resolved my issue:

`getInitialState(){
    return {
      render: false,
      selection: 0
    }
  },
handleSelection(Chart){
    if (Chart.chart.getSelection()[0] ) {
      console.log('Selection: ', Chart.chart.getSelection()[0]['row']);
      this.setState({
        selection : Chart.chart.getSelection()[0]['row']
      })
    }
  },
  componentDidMount(){
    this.setState({
      render: true
    })
  },
  render(){
    if (!this.state.render)
      return null;
    return ( ... what you want )
  }
`

**Comment by davidecarpini** [comment]
from:

https://github.com/RakanNimer/react-google-charts/issues/100#issuecomment-273939149

I resolved it in this way:

```
getInitialState(){
    return {
      render: false,
      selected: null
    }
  },
handleSelection(Chart){
    if (Chart.chart.getSelection()[0] ) {
      console.log('Selection: ', Chart.chart.getSelection()[0]['row']);
      this.setState({
        selected : Chart.chart.getSelection()[0]['row']
      })
    }
  },
  componentDidMount(){
    this.setState({
      render: true
    })
  },
  render(){
    if (!this.state.render)
      return null;
    return ( ... what you want )
  }
```

**Comment by RakanNimer** [comment]
Thanks @davidecarpini for the suggestion ! 

Hope this solves it for you @fk-ajain ?

Closing this for now, feel free to re-open if it still hasn't been resolved.
