### ISSUE TITLE
Demo not working at all

### ISSUE THREAD

**Issue by t47io** [RakanNimer/react-google-charts#137]
react-google-charts 1.5.3
 
I followed exactly the steps for the "Example". First, see an error like this:
```
> example@0.1.0 start /Users/t47/react-google-charts/demo
> react-scripts start

sh: react-scripts: command not found
```

Then I `npm i react-scripts`, and `npm start` can run, but see this error now:
```
Failed to compile.

Error in ../src/components/Chart.js
Module parse failed: /Users/t47/react-google-charts/src/components/Chart.js Unexpected token (347:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (347:6)
 @ ./src/App.js 12:13-50
```

Do I need `webpack` and `babel` globally? No where said. Please fix the demo.

**Comment by t47io** [comment]
BTW, I'm using `node` 7.9.0

**Comment by OracPrime** [comment]
Have you followed the instructions from README.md?

### Run the demo app

Run the demo directory that contains the code powering : http://rakannimer.github.io/react-google-charts/

```bash
  git clone https://www.github.com/rakannimer/react-google-charts
  cd react-google-charts
  npm install
  npm start

**Comment by t47io** [comment]
Yes, I followed exactly these steps. Something is missing in the demo config or readme

**Comment by alexfqc** [comment]
Download the code and try again, I did a pull request and fixed this error

**Comment by RakanNimer** [comment]
Clone repo. Run yarn install then yarn start. Just tested on latest master and it works.
