### ISSUE TITLE
Use UTC Date in Scatter Charts

### ISSUE THREAD

**Issue by chrisdebug** [rakannimer/react-google-charts#138]
I'm using scatter charts and I'm trying to specify my date in UTC. I think it defaults to my browser's timezone. I tried to use "dateFormat" but it doesn't seem to work. Can anyone give me an example of how to do this?

**Comment by jzander** [comment]
@rakannimer  also have this issue, formatters does not seem to work properly 

p.columns.forEach(function (t) {
                        r.applyDateFormat(t, d)
                    })

cannot read property each of undefined

**Comment by rakannimer** [comment]
Hello @chrisdebug  & @jzander,

Sorry for the delay 😅.

[Using formatters demo.](https://react-google-charts.com/formatters)
