### ISSUE TITLE
`loader` always show, even after `draw()`

### ISSUE THREAD

**Issue by t47io** [rakannimer/react-google-charts#141]
The `loader` (default with `'Rendering chart...'`) remains displayed even after the google charts lib has loaded and `draw()` has finished. According to the code, this seems expected:

https://github.com/RakanNimer/react-google-charts/blob/master/src/components/Chart.js#L346
```jsx
  render() {
    debug('render', this.props, this.state);
    const divStyle = {
      height: this.props.height || this.props.options.height,
      width: this.props.width || this.props.options.width,
    };
    return (
      <div id={this.state.graphID} style={divStyle}>
        {this.props.loader ? this.props.loader : 'Rendering Chart...'}
      </div>
    );
  }
```

I understand the difficulty since `draw()` offers no callback. Should we add another boolean `prop` like `shouldShowLoader`? I want to hide this loader, but falsy values will be ignored.

**Comment by rakannimer** [comment]
Hey !

Thanks for reporting the issue.

This should be fixed in latest version (>=2.0).

Feel free to re-open if it re-appears.
