### ISSUE TITLE
Annotated Chart producing errors

### ISSUE THREAD

**Issue by thomashibbard** [rakannimer/react-google-charts#143]
Version

Tell us which versions you are using:

react-google-charts 1.5.5
react v15.3.2
Expected behaviour
Render an annotation chart like found at https://developers.google.com/chart/interactive/docs/gallery/annotationchart
Actual behaviour
Error: `Uncaught (in promise) Error: Failed to set DataTable from data props ! `
Steps to reproduce
1. `import { Chart } from 'react-google-charts'`
2. set `data` to the multidemensional array found in the google doc linked above within the `data.addRows` method
3. put component in render method 
```
<Chart
  chartType='AnnotationChart'
  data={data}
  options={options}
  width='100%'
  height='300px'
>
```
4. load page
     

Link to a git repo that reproduces bug :  https://github.com/thomashibbard/react-googe-chart-render-error1

**Comment by hurcy** [comment]
I also have this error. I hope this issue fixed soon.

**Comment by rakannimer** [comment]
Hey, 

When trying to render more complex charts I recommend you use the new getChartWrapper prop.

Here's a [sandbox you can try out with an example AnnotationChart.](https://codesandbox.io/s/2o70w3p57j)

Hope that helps,
Cheers
