### ISSUE TITLE
Not enough columns given to draw the requested chart

### ISSUE THREAD

**Issue by james-tiqk** [rakannimer/react-google-charts#145]
react-google-charts 1.5.5
react v15.6.1

##Expected behaviour

Chart rendered without any errors in console.

##Actual behaviour

Chart rendered as expected, however, in console there's error:
```
Uncaught Error: Not enough columns given to draw the requested chart.
```

For chart rendering:
```
    <Chart
                  chartType="PieChart"
                  data={[['Age', 'Weight'], ['a', 12], ['b', 5.5]]}
                  options={pieOption}
                  graph_id="PieChart"
                  width={'100%'}
                  height={'400px'}
                  legend_toggle
                />
```

The `pieOption`:

```
    const pieOptions = {
      title: '',
      pieHole: 0.6,
      slices: [
        {
          color: '#2BB673',
        },
        {
          color: '#d91e48',
        },
        {
          color: '#007fad',
        },
        {
          color: '#e9a227',
        },
      ],
      legend: {
        position: 'bottom',
        alignment: 'center',
        textStyle: {
          color: '233238',
          fontSize: 14,
        },
      },
      tooltip: {
        showColorCode: true,
      },
      chartArea: {
        left: 0,
        top: 0,
        width: '100%',
        height: '80%',
      },
      fontName: 'Roboto',
    };
```

What I found is if I removed `fontName: 'Roboto',` from pieOption, the error will disappear.

**Comment by james-tiqk** [comment]
When using a font like `Arial` it works fine. Not sure if this is because Roboto is a web font or something.

**Comment by victorparmar** [comment]
I also have this issue - I'm using Lato :(

**Comment by xiCO2k** [comment]
same issue here using Roboto

**Comment by victorparmar** [comment]
This is still happening ...

**Comment by rakannimer** [comment]
Hey @victorparmar ,

I'm not sure why it's happening on your side, could you please provide me with some code to reproduce it ? 

Hey @james-tiqk,

Here's a working sandbox with the code you provided : https://codesandbox.io/s/vnnwk2pq40

Cheers !

**Comment by victorparmar** [comment]
I upgraded to the latest version and the problem seems to be gone :+1:
