### ISSUE TITLE
Any example to how create Gantt Chart?

### ISSUE THREAD

**Issue by Lorchelio** [rakannimer/react-google-charts#146]
Hi all,

I try to create Gantt-Chart, but some errors like below stop me
**Uncaught (in promise) Error: Invalid type, undefined, for column "0".
Uncaught (in promise) TypeError: this.dataTable.getNumberOfRows is not a function**

My example component:
     <Chart
          chartType="Gantt"
          rows={[
            ['Research', 'Find sources', new Date(2015, 0, 1), new Date(2015, 0, 5),0],
            ['Research', 'Find sources', new Date(2015, 0, 1), new Date(2015, 0, 5),0]
          ]}
          options={{}}
          columns={[
            {'string': '1'},
            {'string': '2'},
            {'date': '3'},
            {'date': '4'},
            {'number': '5'}
          ]}
          graph_id="Gantt"
          width="100%"
          height="400px"
          legend_toggle
        />

**Comment by ajAnshul** [comment]
@RakanNimer I also got same error

**Comment by viktortsarevskiy** [comment]
@Lorchelio, @ajAnshul for your columns data should look like: 
```js
columns={[{type: 'number', label: 'X'}, {type: 'number', label: 'Y'}]}.
```

[Here more info about addColumn method](https://developers.google.com/chart/interactive/docs/reference#DataTable_addColumn)

**Comment by RenukaMP** [comment]
This is my component: 
<Chart
        chartType="Gantt"
        columns={[{"id":"Task ID","type":"string"},{"id":"Task Name","type":"string"},{"id":"Start Date","type":"date"},{"id":"End Date","type":"date"},{"id":"Duration","type":"number"},{"id":"Percent Complete","type":"number"},{"id":"Dependencies","type":"string"}]}
      rows={[["Research","Find sources","2014-12-31T18:30:00.000Z","2015-01-04T18:30:00.000Z",null,100,null],["Write","Write paper",null,"2015-01-08T18:30:00.000Z",259200000,25,"Research,Outline"],["Cite","Create bibliography",null,"2015-01-06T18:30:00.000Z",86400000,20,"Research"],["Complete","Hand in paper",null,"2015-01-09T18:30:00.000Z",86400000,0,"Cite,Write"],["Outline","Outline paper",null,"2015-01-05T18:30:00.000Z",86400000,100,"Research"]]}
        width="100%"
        height="400px"
        chartPackages={["Gantt"]}
      />
i got below error:
loader.js:226 GET https://www.gstatic.com/charts/45.2/js/jsapi_compiled_Gantt_module.js net::ERR_CONNECTION_TIMED_OUT.
Please provide example to create react gantt chart like below link:
[https://developers.google.com/chart/interactive/docs/gallery/ganttchart](https://developers.google.com/chart/interactive/docs/gallery/ganttchart)

**Comment by RenukaB30** [comment]
Here is the  solution:
This is working for me. :)
<Chart
        chartType="Gantt"
        columns={[
      { id: 'Task ID', type: 'string' },
      { id: 'Task Name', type: 'string' },
      { id: 'Start Date', type: 'date' },
      { id: 'End Date', type: 'date' },
      { id: 'Duration', type: 'number' },
      { id: 'Percent Complete', type: 'number' },
      { id: 'Dependencies', type: 'string' },
    ]}
      rows={[
      ['Research', 'Find sources',
        new Date(2015, 0, 1), new Date(2015, 0, 5), null, 100, null],
      ['Write', 'Write paper',
        null, new Date(2015, 0, 9), 3 * 24 * 60 * 60 * 1000, 25, 'Research,Outline'],
      ['Cite', 'Create bibliography',
        null, new Date(2015, 0, 7), 1 * 24 * 60 * 60 * 1000, 20, 'Research'],
      ['Complete', 'Hand in paper',
        null, new Date(2015, 0, 10), 1 * 24 * 60 * 60 * 1000, 0, 'Cite,Write'],
      ['Outline', 'Outline paper',
        null, new Date(2015, 0, 6), 1 * 24 * 60 * 60 * 1000, 100, 'Research'],
    ]}
        width="100%"
        options="{}"
        chartPackages={["gantt"]}
      />
The example data are available in ./src/constants/SAMPLE_DATA.js 
Happy coding !  :)

**Comment by rakannimer** [comment]
[Gantt Chart Example](https://codesandbox.io/s/749lzozz10)
