### ISSUE TITLE
Any way to draw different chart types on a single chart?

### ISSUE THREAD

**Issue by leedstyh** [RakanNimer/react-google-charts#149]
Hi, great package.

Not find a way to draw some different chart types on a single chart, like combine line chart and candlestick chart together. Working like stock chart with some moving average.

Is there any way to do things like this?

I'm using:

react-google-charts 1.5.5
react v15.6.1

**Comment by devbada** [comment]
Have you checked  google combo Chart? (https://developers.google.com/chart/interactive/docs/gallery/combochart )

You can use this 
    `chartType="ComboChart"`

**Comment by leedstyh** [comment]
@devbada Thank you so much. Sorry that new to Google Chats and miss this.
