### ISSUE TITLE
Possible to get data from json?

### ISSUE THREAD

**Issue by CallumBrankin** [rakannimer/react-google-charts#153]
Is it possible to get chart data from a json?

I've just looked here: http://rakannimer.github.io/react-google-charts/#/examples/LineChart?_k=vyma8i
and it appears possible, how can i achieve this?

Alright i figured it out

**Comment by rakannimer** [comment]
For future reference : You can get access to the chart and the dataTable from chartWrapper.

To hold a reference to the chartWrapper use the `getChartWrapper` prop and then you can do everything you can do without React !
