### ISSUE TITLE
How to use  : convertOption in React-google chart, There are some options declared are not finalized in material-chart SUCH AS : isStacked,  Follow instruction , we have to use : google.charts.Bar.convertOptions(options));  but React-google chart is not support 

### ISSUE THREAD

**Issue by toolaugh** [rakannimer/react-google-charts#157]
Version

Tell us which versions you are using:

react-google-charts ?.?.?
react v0.?.?
Expected behaviour

Actual behaviour

Steps to reproduce

1. 2. 3.

Link to a git repo that reproduces bug :

**Comment by dkomanov** [comment]
Here is my workaround:
```
import React from 'react';
import {Chart} from 'react-google-charts';

function getConvertOptionsFunc(chartType) {
  return window.google && window.google.charts && window.google.charts[chartType]
    ? window.google.charts[chartType].convertOptions
    : null;
}

export default class GoogleChart extends React.Component {
  constructor(props) {
    super(props);

    const self = this;

    this.state = {
      convertFunc: getConvertOptionsFunc(self.props.chartType)
    };
    this.chartEvents = [
      {
        eventName: 'ready',
        callback(Chart) {
          const convertFunc = getConvertOptionsFunc(self.props.chartType) || (t => t);
          self.setState({convertFunc});
        },
      },
    ]
  }

  render() {
    const {chartType, options, ...other} = this.props;
    const {convertFunc} = this.state;
    const finalOptions = convertFunc ? convertFunc(options) : options;

    return (
      <Chart chartType={chartType} options={finalOptions} chartEvents={convertFunc ? null : this.chartEvents} {...other}/>
    );
  }
}
```

**Comment by igalarza009** [comment]
Just wanted to express my utter gratitude  to @dkomanov , I have been going crazy for the last couple of days trying to find a solution to a similar problem, and your propopsed workaround worked perfectly for me. Thank you!

**Comment by evandegr** [comment]
Were you loading google charts into the page elsewhere? `google` is not attached to my `window`, so this isn't working for me.

**Comment by selvinsmart** [comment]
> Here is my workaround:
> 
> ```
> import React from 'react';
> import {Chart} from 'react-google-charts';
> 
> function getConvertOptionsFunc(chartType) {
>   return window.google && window.google.charts && window.google.charts[chartType]
>     ? window.google.charts[chartType].convertOptions
>     : null;
> }
> 
> export default class GoogleChart extends React.Component {
>   constructor(props) {
>     super(props);
> 
>     const self = this;
> 
>     this.state = {
>       convertFunc: getConvertOptionsFunc(self.props.chartType)
>     };
>     this.chartEvents = [
>       {
>         eventName: 'ready',
>         callback(Chart) {
>           const convertFunc = getConvertOptionsFunc(self.props.chartType) || (t => t);
>           self.setState({convertFunc});
>         },
>       },
>     ]
>   }
> 
>   render() {
>     const {chartType, options, ...other} = this.props;
>     const {convertFunc} = this.state;
>     const finalOptions = convertFunc ? convertFunc(options) : options;
> 
>     return (
>       <Chart chartType={chartType} options={finalOptions} chartEvents={convertFunc ? null : this.chartEvents} {...other}/>
>     );
>   }
> }
> ```

I get the following error:
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by ColdTuna** [comment]
Change the constructor if you are getting infinite update, like this works:

    constructor(props) {
        super(props);

        const self = this;

        // CHANGE HERE: 
        this.state = {
            convertFunc: "" // don't initialize it quite yet
        };

        this.chartEvents = [
            {
            eventName: 'ready',
            callback(Chart) {
                    // AND CHANGE HERE: 
                    if(!this.state.convertFunc) {  // when chart is ready, then initialize it
                        const convertFunc = getConvertOptionsFunc(self.props.chartType) || (t => t);
                        self.setState({convertFunc});
                    }
                },
            },
        ]
    }

**Comment by pfuersattel** [comment]
I ran into a similar issue. I could not get the class based solution above running, but a functional component seems to work well:
```
import React from "react";
import { Chart } from "react-google-charts";

function getConvertOptionsFunc(chartType) {
  return window.google &&
    window.google.charts &&
    window.google.charts[chartType]
    ? window.google.charts[chartType].convertOptions
    : null;
}

const GoogleChart = function (props) {
  const [convertedOptions, setConvertedOptions] = React.useState(null);
  const { chartType, options, ...other } = props;
  const finalOptions = convertedOptions === null ? options : convertedOptions;

  const chartEvents = [];

  if (convertedOptions == null && props.convertOptions)
    chartEvents.push({
      eventName: "ready",
      callback(Chart) {
        const func = getConvertOptionsFunc(props.chartType);
        setConvertedOptions(func(props.options));
      }
    });

  return (
    <Chart
      chartType={chartType}
      options={finalOptions}
      chartEvents={chartEvents}
      {...other}
    />
  );
};

GoogleChart.defaultProps = {
  convertOptions: false
}

export default GoogleChart;
```
