### ISSUE TITLE
How to create GaugeCharts?

### ISSUE THREAD

**Issue by ppandatw** [rakannimer/react-google-charts#159]
Version

Tell us which versions you are using:

react-google-charts 1.5.5
react v15.5.4

How to create GaugeCharts?
I've used 
`chartType="GaugeChart"`
`chartPackages={['corechart', 'timeline', 'gauge']}`

But its not working. Its showing 
_    Invalid visualization type: GaugeChart
    Rendering Chart_
 There exists gauge charts in original  [google charts](https://developers.google.com/chart/interactive/docs/gallery/gauge)

**Comment by Nekromancer** [comment]
```
chartType="Gauge"
chartPackages={['gauge']}
```

It's working for me

**Comment by rakannimer** [comment]
Example of a Gauge Chart with animations on value change : 

https://codesandbox.io/s/ykzvw2yv3z


```javascript
		<Chart
          chartType="Gauge"
          width="100%"
          height="400px"
          data={[
		      ["Label", "Value"],["Memory", this.state.memory],["CPU", this.state.cpu], ["Network", this.state.networkSpeed]
		  ]}        />
```
