### ISSUE TITLE
Using with React 16 (until 1.5.6 is published)

### ISSUE THREAD

**Issue by taylorham** [rakannimer/react-google-charts#161]
This is a tip moreso than an issue. I just wanted to share with anyone else who wanted to upgrade their apps to the latest React and is facing an issue with dependencies requiring older versions.

[This link](https://yarnpkg.com/en/docs/selective-version-resolutions#toc-how-to-use-it) has all of the steps to fix it, but the short version is to add this in your `package.json`:

```json
  "dependencies": {...},
  "resolutions": {
    "react-google-charts/react": "16.0.0",
    "react-google-charts/react-dom": "16.0.0"
  },
```

**Comment by RakanNimer** [comment]
Awesome, thanks for sharing that !

As an FYI, I haven't had time to publish the next version yet, I'd like it to be much more solid and better-tested but I haven't had any time to put into open source lately.

Will update here, when it's ready, with React 16 support :) 

Cheers !

**Comment by SiqiTian-minted** [comment]
Publish `1.5.6` to NPM?

**Comment by taylorham** [comment]
Hey @RakanNimer ! I know you're probably a busy guy, but do you have any plans to publish 1.5.6 in the near future?

I keep eyeing that `resolutions` property in my `package.json` wondering when I can shave those four lines off our codebase! 😝

**Comment by squadette** [comment]
I'm using:

````
"react-google-charts": "https://github.com/squadette/react-google-charts/tarball/master",
````

in `package.json`.  It is kinda awkward but it works until master is fixed.

**Comment by rakannimer** [comment]
Latest on npm should work with any React version >= 15.0.0
