### ISSUE TITLE
will this work with react native?

### ISSUE THREAD

**Issue by NasarudinAbdulShukor** [rakannimer/react-google-charts#168]
Version

Tell us which versions you are using:

react-google-charts 1.5.5
react 16.0.0-beta.5
react-native https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz
Expected behaviour:

I am trying this library with react native. I import it together with react and react native . Below is the my test code.

    import React, { Component } from 'react';
    import { View } from 'react-native';
    import { Chart } from 'react-google-charts';

    class TestChart extends Component {
        render() {
             return (
                <View>
                    <Chart
                        /* scatter chart example */
                    />
                 </View>
             )
          };
       }
    export default TestChart;

I am expecting it to show on my phone screen or simulator.

Actual behaviour

I see following error : 
    Body:
    {"message":"TransformError: /Users/Nasarudin/workspace/chartapp/node_modules/react-google-charts/lib/index.js:[BABEL]/Users/Nasarudin/workspace/chartapp/node_modules/react-google-charts/lib/index.js:Unknown option:/Users/Nasarudin/workspace/chartapp/node_modules/react-google-charts/react/react.js.Children.Check out ....}

Is this because this library can't work with react-native or did I miss something?
Thank you

**Comment by rakannimer** [comment]
Unfortunately no, Google Charts works only on web.

**Comment by jsah9105** [comment]
you can load google-charts in react-native WebView
