### ISSUE TITLE
Using other google charts methods

### ISSUE THREAD

**Issue by fcostarodrigo** [rakannimer/react-google-charts#169]
react-google-charts 1.5.5
react 16.0.0

Where and when methods like `window.google.visualization.arrayToDataTable` are available for use?

**Comment by rakannimer** [comment]
I'll be shipping a new release that provide access to window.google when it's safe.

Meanwhile you can use the getChartWrapper prop to get access to the chartWrapper, and in the callback you should be able to use window.google.visualization.arrayToDataTable without any problems.

**Comment by rakannimer** [comment]
Starting from `2.20` You can access any methods on `google` in getChartWrapper. 

`getChartWrapper` is called with 2 arguments, the chartWrapper instance and google from window. 

Will be adding this to the docs soon.

Cheers !
