### ISSUE TITLE
IE 11 issue - Promise is undefined

### ISSUE THREAD

**Issue by deepfriedbrain** [rakannimer/react-google-charts#170]
I'm using version 1.5.5 of react-google-charts. Charts are not rendering on IE 11 and I get Promise is undefined error in the Dev console. I understand that Bluebird dependency was removed in version 1.5.2. My project is using Babel and I'm using Promise in many other parts of my code without any problem.

What do I need to get Promise to for react-google-charts and get the charts to render? 

Thanks.

**Comment by jimulle** [comment]
Have you tried [babel-polyfill](https://www.npmjs.com/package/babel-polyfill)?
I use it in my webpack build with `react-google-charts` in my app and I haven't experienced the `Promise is undefined` error.

**Comment by squadette** [comment]
You can also try `babel-plugin-transform-promise-to-bluebird`.
