### ISSUE TITLE
regionClick for geochart not working

### ISSUE THREAD

**Issue by webmaxdev0110** [rakannimer/react-google-charts#173]
Version

Tell us which versions you are using:

react-google-charts 1.5.5
react v15.5.4
**Expected behaviour**
```
getChartEvent = () => {
    return [
      {
        eventName: 'regionClick',
        callback: (Chart) => {
          //console.log(Chart.region)  //Chart.region should return region according to google doc but returns undefined
          this.props.onRegionClick(Chart.region)
        },
      },
    ]
  }
```

**Actual behaviour**
Chart.region returns undefined in callback

**Comment by indrajit-rathod** [comment]
Any solution for this. I am also facing the same issue.

**Comment by JohannesCogitel** [comment]
I don't know if this will help but using v1.6.6 i can get selected region data from the second callback argument.
Like so.
            {
                eventName: 'regionClick',
                callback(Chart, selected) {
                    console.log('Region selected ', selected.region);
                }
            }

**Comment by rakannimer** [comment]
Starting from >v2.0 you can get access to the selected region from the third argument : 

```
{
eventName: 'regionClick',
callback(chartWrapper, googleViz, selected) {
console.log('Region selected ', selected.region);
}
}
```
