### ISSUE TITLE
onClick event handler to Tables

### ISSUE THREAD

**Issue by prasadmes** [rakannimer/react-google-charts#175]
How click i handle click when the user clicks on achor tag in particular td?

I tried something like this but no success

``<a href='#' onClick=${() = > this.handleClick}> Click me!! </a>``

**Comment by rakannimer** [comment]
You should probably add an events array to the props and listen to `select` event.

Maybe [this](https://github.com/rakannimer/react-google-charts#listen-to-chart-events) is helpful ?
