### ISSUE TITLE
compile different language version in npm

### ISSUE THREAD

**Issue by cnavarreteliz** [rakannimer/react-google-charts#177]
Hi, I'm using RGC for a personal project, and I tried to use Gantt in spanish, but in `npm` doesn't available version with fix of languaje.

And I tried to install vía `"react-google-charts": "git+https://github.com/RakanNimer/react-google-charts.git"` using `npm i` but I got:

```
Module parse failed: Unexpected token (379:6)You may need an appropriate loader to handle this file type.
|     };
|     return (
|       <div id={this.state.graphID} style={divStyle}>
|         {this.props.loader ? this.props.loader : 'Rendering Chart...'}
|       </div>
```

Regards,

**Comment by rakannimer** [comment]
Hey ! 

Sorry for that, new version is published on npm !
