### ISSUE TITLE
Invalid visualization type: DonutChart, PieChart

### ISSUE THREAD

**Issue by tewrisFront** [rakannimer/react-google-charts#178]
Version

Tell us which versions you are using:

react-google-charts 1.5.5
react "^15.6.1
Expected behaviour

Actual behaviour

Steps to reproduce

1. 2. 3.

Link to a git repo that reproduces bug :

**Comment by rakannimer** [comment]
Examples : 

[Donut Chart](https://github.com/rakannimer/react-google-charts#donut-chart)
[Pie Chart](https://github.com/rakannimer/react-google-charts#pie-chart)
