### ISSUE TITLE
Demo Failed to compile.

### ISSUE THREAD

**Issue by lfelipequiros** [rakannimer/react-google-charts#180]
Version

**Tell us which versions you are using:**

    "react-google-charts": "1.5.2"
    "react": "^15.4.2",

**Expected behaviour**
DEMO compile and run 

**Actual behavior**
Failed to compile.

Error in ../src/components/Chart.js
Module parse failed: C:\dev\play\react-google-charts\src\components\Chart.js Unexpected token (379:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (379:6)
 @ ./src/App.js 12:13-50

**Steps to reproduce**

https://www.npmjs.com/package/react-google-charts

git clone https://www.github.com/rakannimer/react-google-charts
cd react-google-charts/demo
npm link ../
npm install
npm start

Is the npm package info updated? am I missing something to make it run?

**Comment by rakannimer** [comment]
Should be fixed in v2 ! Thanks for reporting :)
