### ISSUE TITLE
Table: page and pageSize and other props

### ISSUE THREAD

**Issue by newfylox** [rakannimer/react-google-charts#181]
Do you think there's a chance you will update props that `Chart` component can receive? It would be a good idea that any passed props to the component is dynamically converted to Google Charts configuration options so that it will always be synced with last Google Charts release.

For example, I use `page` and `pageSize` props as explained on [https://developers.google.com/chart/interactive/docs/gallery/table](https://developers.google.com/chart/interactive/docs/gallery/table) but it does nothing.

Thanks!

**Comment by rakannimer** [comment]
You can pass these arguments in the options prop. 

[Table Chart Example.](https://github.com/rakannimer/react-google-charts#table-chart)
