### ISSUE TITLE
vAxis not respecting maxValue set in options

### ISSUE THREAD

**Issue by glennmartinez** [rakannimer/react-google-charts#182]
I'm unable to set a maxValue on the vertical axis as below.

I have a stream of data with average value of around 3000 but two or more value are over 100,000. This means that my line chart has a top vertical value of 160,000 making the bulk of the values unreadable.

I set the max to 5000 but it doesn't respect it, On another chart with less variance on the data it seems to work, there seems to be a ceiling value ie: max value + 20% or something which the maxValue can't override.

` options: {
                title: 'Age vs. Weight Comparison',
                hAxis: { title: 'Age' },
                vAxis: { title: 'Weight', minValue: 0, maxValue: 100000 },
                legend: 'none',
            }`

Version

Tell us which versions you are using:

react-google-charts 1.5.5
react v15.6.2

**Comment by SomeVlad** [comment]
Faced the same issue, seems like its fix is to set `vAxis: { viewWindow: { max: 100000 } }`.

**Comment by rakannimer** [comment]
I think this is more of a Google Charts question, not sure if I can help.
