### ISSUE TITLE
Invalid prop `data` of type `object` supplied to `Chart`, expected an array.

### ISSUE THREAD

**Issue by kevinstembridge** [rakannimer/react-google-charts#185]
react-google-charts 1.5.7
react v16.2.0

When I pass a JSON string to the data property of the Chart component I get the following error:

    Invalid prop `data` of type `object` supplied to `Chart`, expected an array.

This is because of the PropTypes declaration for the data property:

    
    Chart.propTypes = {
        ...  
    data: PropTypes.arrayOf(PropTypes.array),

The data property is passed to the underlying ChartWrapper.setDataTable method from the Google Charts library. This method accepts the following:

    Sets the DataTable for the chart. Pass in one of the following: null; a DataTable object; a JSON representation of a DataTable; or an array following the syntax of arrayToDataTable().

https://developers.google.com/chart/interactive/docs/reference#methods_4

The Chart.propTypes should probably be modified to accept the same types as the ChartWrapper.setDataTable method.

Happy to provide a pull request if you want one.

**Comment by kevinstembridge** [comment]
Hi,
I just tried v2.0.12 and I now get a different error.

"Not an array"

I'm passing the following data object.

{"cols":[{"id":"X","label":"Month","type":"string"},{"id":"count","label":"Activation Count","type":"number"}],"rows":[{"c":[{"v":"2018-07"},{"v":19}]}]}

...as per the documentation here:
https://developers.google.com/chart/interactive/docs/reference#dataparam

This was working fine with v1.

Should I raise a new ticket?

**Comment by rakannimer** [comment]
Oh okay, that makes sense. 

You need to either provide that object as rows and columns : 

```javascript
        <Chart
          chartType="BarChart"
          width="100%"
          height="400px"
          columns={[
            { id: "X", label: "Month", type: "string" },
            { id: "count", label: "Activation Count", type: "number" }
          ]}
          rows={[{ c: [{ v: "2018-07" }, { v: 19 }] }]}
/*
OR
		  data={[
            { id: "X", label: "Month", type: "string" },
            { id: "count", label: "Activation Count", type: "number" }
           ], 
		   [{ c: [{ v: "2018-07" }, { v: 19 }] }]
          }
*/
        />
```


Here's an [example sandbox](https://codesandbox.io/s/9o8jy5959r)

Cheers !

**Comment by kevinstembridge** [comment]
I think I'll start a new thread to talk about supporting the DataTable object syntax. 

Thanks.
