### ISSUE TITLE
Add ability to set CSS class of container element

### ISSUE THREAD

**Issue by Mark-Hetherington** [rakannimer/react-google-charts#188]
Version

Tell us which versions you are using:

react-google-charts 1.5.7
react v16.2.0
Expected behaviour
Able to set CSS Class on google chart dev element

Actual behaviour
className attribute not honoured. 

Steps to reproduce

1. 
`<Chart
            chartType="BarChart"
            graph_id={this.id}
            data={chart_data}
            className="google-chart"
        />`

Use Case:
If the width and height are set to {null} it would be possible to target the charts element with a CSS stylesheet to set a consistent display size across multiple charts. It might make sense for the chartType to be included with any specified CSS class names.

**Comment by rakannimer** [comment]
Yeah that's a great idea ! 

Working on it.

**Comment by rakannimer** [comment]
Added `style` and `className` props. You can use them to style the container div starting 2.0.12.

Cheers !
