### ISSUE TITLE
Gantt Chart custom tooltips and colors

### ISSUE THREAD

**Issue by maro512** [rakannimer/react-google-charts#189]
Version
react-google-charts 1.5.7
react 16.2.0

Hi, it is possible to create your own tooltips? I added new column, like bellow:
`{
          id: 'tmp',
          type: 'string',
          role: 'tooltip',
          p: {
            html: true
          }
}`
and corresponding rows and I can see default tooltip instead of mine. My options looks like below
```
{
    height: (rows.length + 1) * 25,
    width: 320 + days * 15,
    gantt: {
      trackHeight: 25,
      barHeight: 18,
      barCornerRadius: 1.5,
      arrow: {
        length: 6,
        spaceAfter: 2,
        radius: 3,
      },
    },
    colors: ['#111111', '#222222', '#333333', '#444444', '#555555', '#666666', '#777777', '#888888'],
    tooltip: {
      isHtml: true
    }
  }
```
I set also colors, but bars have defaults colors.

Thanks for your help in advance.
Marek

**Comment by rakannimer** [comment]
Sorry for that ! 

Should be fixed in v2.

Please feel free to re-open if it isn't

**Comment by areohbe** [comment]
I am running into to the same issue. My columns array looks like:
```
const columns = [
    { type: 'string', label: 'Task Id' },
    { type: 'string', label: 'Task Name' },
    { type: 'string', label: 'Resource' },
    { type: 'date', label: 'Start' },
    { type: 'date', label: 'End' },
    { type: 'number', label: 'Duration' },
    { type: 'number', label: 'Percent Complete' },
    { type: 'string', label: 'Dependencies' },
    { type: 'string', role: 'tooltip' }
  ];
```
Do I need to set something in the `options` as well?

**Comment by mrkchang** [comment]
> I am running into to the same issue. My columns array looks like:
> 
> ```
> const columns = [
>     { type: 'string', label: 'Task Id' },
>     { type: 'string', label: 'Task Name' },
>     { type: 'string', label: 'Resource' },
>     { type: 'date', label: 'Start' },
>     { type: 'date', label: 'End' },
>     { type: 'number', label: 'Duration' },
>     { type: 'number', label: 'Percent Complete' },
>     { type: 'string', label: 'Dependencies' },
>     { type: 'string', role: 'tooltip' }
>   ];
> ```
> 
> Do I need to set something in the `options` as well?

Did you get this to work?

**Comment by alex5207** [comment]
Any news on this one?

**Comment by pohsiu** [comment]
+1

**Comment by pohsiu** [comment]
I found this
https://developers.google.com/chart/interactive/docs/customizing_tooltip_content#supported-charts
Seems tooltip customization doesn't support gantt chart.

**Comment by darewreck54** [comment]
> { type: 'string', role: 'tooltip' }

Was this ever supported? or will it be supported?
