### ISSUE TITLE
Google Chart Default Tooltip Bug: Value overwrites Attribute

### ISSUE THREAD

**Issue by FabianSchuessler** [rakannimer/react-google-charts#198]
There seems to be an issue with the coordinates of the second part of the tooltip key-value pair.

![image](https://user-images.githubusercontent.com/10107422/40303253-5670e7e0-5cf2-11e8-9e7d-5313011af355.png)

Does anyone have an idea if this is maybe just a problem on my side or how can I fix this?

**Comment by FabianSchuessler** [comment]
This issue is due to overwriting the default font with a wider font.
Strangely this bug can be mitigated by setting all chart tooltips html = true.

```
                                      tooltip: {
                                          isHtml: true,
                                      },
```

**Comment by rakannimer** [comment]
This seems more like an issue with Google Charts as opposed to this library.
Cheers !
