### ISSUE TITLE
text color issue

### ISSUE THREAD

**Issue by tewrisFront** [rakannimer/react-google-charts#200]
Hello
I am going to create chart like this.
Please let me know.
How can I change text color
![screen shot 2018-05-31 at 10 37 25 pm](https://user-images.githubusercontent.com/29981973/40806977-57c10ff6-6523-11e8-9864-855f61b2f91c.png)

**Comment by rakannimer** [comment]
You can configure the color using the options props. [Full PieChart Google reference](https://developers.google.com/chart/interactive/docs/gallery/piechart)
