### ISSUE TITLE
"Rendering Chart" warning div appears when parent component changes state or re-renders

### ISSUE THREAD

**Issue by aalises** [rakannimer/react-google-charts#202]
Hello!

I have a chart inside a component and I want to update the options of the chart based on the state. However, each time the state changes and triggers a re-render of the component, a **"Rendering Chart"** div appears on top of the chart, but the content is updated correctly. That div only goes away when reloading the page. I think it might be related to #195 or #197 

Also, when switching to another page (unmounting the component) and going back to the same page mounting it again, the loaders.js errors appear again...

**Comment by blakes7** [comment]
Similar problem here. Switching away from page and going back cause's the loader.js error message to appear.

**Comment by rakannimer** [comment]
This should be fixed in latest version (>=2.0).

Feel free to re-open if it re-appears.

**Comment by orian** [comment]
I'm having this issue on version 2.0.29. I have two components, each of them contains a chart. Only one chart renders correctly. There is no trace in console. Refreshing the page causes one of the charts to be rendered and the other one to be left with "Rendering Chart" text.
