### ISSUE TITLE
top-x chart is not working

### ISSUE THREAD

**Issue by ArpiJakab** [rakannimer/react-google-charts#203]
Tried to move the x-axis to the top as suggested here https://developers.google.com/chart/interactive/docs/gallery/barchart#top-x-charts

x-axis remains on the bottom, here is my JSX snippet. 
` <Chart
					data={[
			          ['Opening Move', 'Percentage'],
				  ]}
				  chartType='BarChart'
				  options={{
					  title: 'Chess opening moves',
			          width: 900,
			          legend: { position: 'none' },
			          chart: { title: 'Chess opening moves',
			                   subtitle: 'popularity by percentage' },
			          bars: 'horizontal',
			          axes: {
			            x: {
			              0: { side: 'top', label: 'Percentage'}
			            }
			          },
			          bar: { groupWidth: "90%" }
				  }}
				  width='100%'
				  height='200px'
				  legend_toggle
				 />`

**Comment by rakannimer** [comment]
Should work in V2. Please feel free to re-open if it doesn't !

**Comment by mariobrubio** [comment]
This is not working yet, please re-open the issue
