### ISSUE TITLE
Gauge isn't working?

### ISSUE THREAD

**Issue by bradynapier** [RakanNimer/react-google-charts#21]
Trying to render a gauge and it is not working at all.  Not sure what I might be doing incorrectly here.
import React, { Component, PropTypes } from 'react';
      
      import { Chart } from 'react-google-charts';
      
      class NetworkGauge extends Component {
      
        componentDidMount() {
          this.renderChart();
        }
      
        constructor(props, context) {
          super(props, context);
          this.state = {
            data: [],
            options: {},
          }
        }
      
        renderChart() {
          const data = [
             ['Label', 'Value'],
             ['Memory', 80],
             ['CPU', 55],
             ['Network', 68]
          ];
      
          const options = {
             redFrom: 90, redTo: 100,
             yellowFrom:75, yellowTo: 90,
             minorTicks: 5
          };
      
          this.setState({
             'data' : data,
             'options' : options
          });
      
        }
      
        render() {
          console.log(this.state.data);
          return (
            <Chart chartType="Gauge" data ={this.state.data} options={this.state.options} graph_id="Gauge" width={"100%"} height={"400px"}>
            </Chart>
          );
        }
      }
      
      export default NetworkGauge;

**Comment by RakanNimer** [comment]
Hey,

It looks like a problem with the syntax : 

```        <Chart chartType="Gauge" data ={this.state.data} options={this.state.options} graph_id="Gauge" width={"100%"} height={"400px"}>
```
Should be =>

```        <Chart chartType={"Gauge"} data ={this.state.data} options={this.state.options} graph_id="Gauge" width={"100%"} height={"400px"}>
```

Could you update if this worked with you ?

**Comment by RakanNimer** [comment]
I think the problem is because Gauge requires you to load the Gauge package. 

Please try adding chartPackages={"['gauge']"}

**Comment by moisesStevend** [comment]
import React,{Component} from 'react'
import { Chart } from 'react-google-charts';

export default  class Gauge extends Component{
  render(){
    return(
      <div>
        <Chart
          chartType="Gauge"
          data={[
            ['Label', 'Value'],
            ['Memory', 80],
            ['CPU', 55],
            ['Network', 68]
          ]}
          options={{
              width: 400, height: 120,
              redFrom: 90, redTo: 100,
              yellowFrom:75, yellowTo: 90,
              minorTicks: 5
            }}
          graph_id="gauge"
          width="100%"
          height="400px"
          legend_toggle
        />
      </div>
    )
  }
}
/*
<Chart
  chartType="ScatterChart"
  data={[
          ['Age', 'Weight'],
          [8, 12],
          [4, 5.5]
        ]}
  options={{}}
  graph_id="ScatterChart"
  width="100%"
  height="400px"
  legend_toggle
/>
*/

this code works on my pc
