### ISSUE TITLE
Example Site Down

### ISSUE THREAD

**Issue by preludeofme** [rakannimer/react-google-charts#210]
https://rakannimer.github.io/react-google-charts/#/examples/Gantt?_k=wu1nit 

showing 404 for me. not sure if you're switching to a new host or something

**Comment by rakannimer** [comment]
Hey ! 

Thank you for reporting this, I'm currently working on some new documentation. Meanwhile here's a working example of a Gantt Chart : 

[CodeSandbox](https://codesandbox.io/s/749lzozz10)

[Google Charts Reference](https://developers.google.com/chart/interactive/docs/gallery/ganttchart)
