### ISSUE TITLE
Add support for Javascript literal object passed to DataTable

### ISSUE THREAD

**Issue by kevinstembridge** [rakannimer/react-google-charts#211]
Version 1.x of react-google-charts supported the passing of a Javascript literal object to the chart in the format expected by the DataTable class.

See
https://developers.google.com/chart/interactive/docs/reference#dataparam

This no longer works in v2. Is it possible to add support back in?

**Comment by rakannimer** [comment]
Yep ! Released in `2.0.13`

**Comment by kevinstembridge** [comment]
Fantastic! That did the trick. Thanks for the fast turnaround.
