### ISSUE TITLE
Events doesn't provide any arguments on callback and didn't work with chartEvents

### ISSUE THREAD

**Issue by DWboutin** [rakannimer/react-google-charts#212]
Hi

I tried to set some events like it's explained here https://github.com/rakannimer/react-google-charts#listen-to-chart-events but nothing works.

First, you don't need to put events in `chartEvents={chartEvents}` but in `events={chartEvents}`. So I set the events in `events`, when the component mounts, it doesn't trigger the `ready` event, it only trigger it on update.

Secondly, there's no arguments provided in the callback. I created these events to test them:

```javascript
const chartEvents = [
  {
    eventName: "select",
    callback() {
      console.log("Selected ", arguments, this);
    }
  },
  {
    eventName: "ready",
    callback() {
      console.log("Ready ", arguments, this);
    }
  }
];
```

Both event logs:
<img width="538" alt="screen shot 2018-07-24 at 4 03 55 pm" src="https://user-images.githubusercontent.com/1322006/43163245-8f0aef1a-8f5b-11e8-87e3-80d86347726c.png">

This is my complete code. Yes I know it's called BarChart, but I was just testing the wrapper.
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import { Chart } from "react-google-charts";

const chartEvents = [
  {
    eventName: "select",
    callback(...args) {
      console.log("Selected ", args, this);
    }
  },
  {
    eventName: "ready",
    callback(...args) {
      console.log("Ready ", args, this);
    }
  }
];
const data = [
  ["age", "weight"],
  [8, 12],
  [4, 5.5],
  [11, 14],
  [4, 5],
  [3, 3.5],
  [6.5, 7]
];

const options = {
  title: "Age vs. Weight comparison",
  hAxis: { title: "Age", viewWindow: { min: 0, max: 15 } },
  vAxis: { title: "Weight", viewWindow: { min: 0, max: 15 } },
  legend: "none"
};

function BarChart() {
  return (
    <div className="chart-container">
      <Chart
        chartType="ScatterChart"
        data={data}
        options={options}
        graphID="ScatterChartt"
        width="100%"
        height="400px"
        events={chartEvents}
        chartEvents={chartEvents}
      />
    </div>
  );
}

export default BarChart;
```

**Comment by rakannimer** [comment]
Hey @DWboutin,

Thanks for reporting ! You're absolutely right, can you try with version `2.0.15`

I renamed it back to chartEvents and passed 3 arguments to the callback : 

1 - Google Chart Wrapper
2 - Google from window (for access to any visualization method or class)
3 - Event args received from the event.

Cheers !

**Comment by DWboutin** [comment]
Thank you!
