### ISSUE TITLE
unit testing support

### ISSUE THREAD

**Issue by darpanpathak** [rakannimer/react-google-charts#214]
While testing with Jest and Enzyme SVG inside chart is not rendering with mount or shallow.

**Comment by rakannimer** [comment]
Hey @darpanpathak, 

The Google Charts library is highly dependent on the DOM, so you won't be able to render the actual chart in your jest tests (which are running in either node or jsdom). 

I suggest you mock the Chart component and just make sure it receives the right props if you want to stick to unit testing your wrapper component. 

If you want to make sure the chart renders than you're going to need to some e2e tests with Cypress or Puppeteer.

Cheers !
