### ISSUE TITLE
Charts with multiple data series?

### ISSUE THREAD

**Issue by moaiii** [rakannimer/react-google-charts#217]
Hi! 

Is it possible to create a column chart with multiple data series.

For example https://jsfiddle.net/63jx9u71/

<img width="672" alt="screen shot 2018-07-30 at 12 07 36" src="https://user-images.githubusercontent.com/12732217/43394048-318335e2-93f1-11e8-954b-62453425bd9e.png">

When using the react-google-charts column chart sandbox I cant seem to be able to get anything but one series.

**Comment by rakannimer** [comment]
Hey @moaiii, 

You definitely can, I reproduced your example [here](https://codesandbox.io/s/5250210jkk).

Let me know if it's not clear.

Cheers !

**Comment by moaiii** [comment]
Amazing! Thanks for the quick reply @rakannimer
