### ISSUE TITLE
charts not displaying, no error message shown

### ISSUE THREAD

**Issue by caseyahlan** [rakannimer/react-google-charts#218]
My charts aren't showing up, and no error message is being shown.

Here's some of my code:

        getUPS(evt) {
        evt.preventDefault();
        fetch(url + document.getElementById("time").value, {

        })
            .then(results => {
                return results.json();
            }).then(data => {
                data = data.value;
                var data2 = new google.visualization.DataTable();
                data2.addColumn("string", "timestamp");
                data2.addColumn("string", "name");
                data2.addColumn("string", "trackingId");
                for (let i = 0; i < data.length; i++) {
                    data2.addRow([data[i].timestamp, data[i].customEvent.name, data[i].customDimensions.trackingId]);
                }
 
                this.setState({
                    data7: data2});
                console.log(data2);
                document.getElementById("datatable").style.display = "block";
            })
    }

          render() {
            return (
                       <div style={{ display: 'none' }} id="tablechart" className={'chart'}>
                                 <Chart
                              chartType="Table"
                                  data={this.state.data7}
                               options={this.state.options2}
                                  width="1600px"
                              height="1000px"
                           /> 
                           </div>
                )}

Any idea what could be happening?

**Comment by rakannimer** [comment]
Hey @caseyahlan,

it looks like you're creating and passing the DataTable to React Google Charts, you don't need to do that. 

In your example : 

```javascript

var data2 = [
	[
		"timestamp",
		"name",
		"trackingId"
	]
]
for (let i = 0; i < data.length; i++) {
	data2.push([data[i].timestamp, data[i].customEvent.name, data[i].customDimensions.trackingId]);
}
this.setState({
	data7: data2
});

```

You can check an example of a Table [here](https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/table)

Cheers !
