### ISSUE TITLE
Diff charts no longer working in 2.0.20

### ISSUE THREAD

**Issue by kkerley** [rakannimer/react-google-charts#219]
I had been using version 1.5.7 prior to today and finally upgraded to 2.0.20 this morning because I needed HTML tooltips for a chart and those weren't added until the 2.0 release a few days ago.

I've written custom component wrappers because the charts for this application require pagination and the ability to change the scope of data shown (weekly, monthly, all-time). The custom component wrappers take the initial data being returned from the API and then do some processing for default data scope (weekly) which sets up each week's 'page' of data. Each page of data is a smaller, self-contained data table with the first row containing the headers and each subsequent row containing the relevant data. Upon clicking to the next/previous page, the state updates the currentPageNum value which in turn updates the diffdata attribute which uses the full arrays of returned data for the data being compared, paged by week number of the year (through Momentjs), and filtered down to a single array each for old and new data.

Following the discussion here in [#76](https://github.com/rakannimer/react-google-charts/issues/76) I was able to get diff charts working by providing the chart a diffdata property with an object containing an object with two keys:

`diffdata: { old: pagedScheduled[page], new: pagedCompleted[page] }`

A few other bits of state are updated as well and the chart is using

`diffdata={this.state.diffdata}` 

So it should be re-rendering each time pagination or data scope is changed. And pagination and data scope filtering works just fine, the chart just never renders no matter what.

It worked perfectly and exactly as expected in 1.5.7 however now in 2.0.20, the exact same code results in "Rendering chart..." indefinitely. I'm providing the diffdata object via a function that runs in componentDidMount() as well as any time the pagination is changed and/or the data scope (weekly, monthly, all-time) is changed, yet the chart never renders.

There are no errors thrown in the console.

**Comment by kkerley** [comment]
I reverted to 1.5.7 and now suddenly HTML tooltips are working. I have no idea why but I guess I'm going to stick with this version now.

**Comment by rakannimer** [comment]
Hey @kkerley, 

Thanks for reporting, If I'm not mistaken, I think just changing the props will diff the data. 

What's the expected behaviour ? Would it work by just passing in the new data to render as props ?

Cheers :)

**Comment by kkerley** [comment]
@rakannimer what do you mean "changing the props will diff the data"? I have to process the data to be the appropriate time period and use the 'completed' and 'scheduled' bits of data because I'm not showing old/new, but rather a list of dates with x number of scheduled tasks and y number of completed tasks for a patient, with scheduled set to `old` and completed set to `new` and passed into the component's state as `diffdata: { old: scheduled, new: completed }` which is then passed to the chart's diffdata prop.

In 1.5.7, this works perfectly and exactly as expected.

In 2.0.20, it is forever stuck at "Rendering chart..." and despite logging the output to the browser console and seeing that the same arrays that work in 1.5.7 are present and the component's state is updating properly which should be in turn updating the chart's props to have the correct diffdata, it never renders the chart.

**Comment by rakannimer** [comment]
My bad ! I misunderstood what you were asking, you were talking about [Google Diff Charts](https://developers.google.com/chart/interactive/docs/gallery/diffchart) and I understood it as diffing the data between consecutive renders !

You're right v2.0.20 did not have support for diffdata. Can you try `2.0.21`, should work as expected.

[Sandbox](https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/diff-chart)

**Comment by kkerley** [comment]
I ran
`npm install react-google-charts@latest` and got this output:

`react-google-charts@2.0.21  invalid`

I changed my package.json file to use 2.0.21 and started up the local server again and it's the same thing as 2.0.20: diff charts forever say "Rendering chart..." There are no errors in the console. I looked at your sandbox example and it looks like my code with the data being slightly different of course, but when I change your sandbox chart's `chartType` to 'ColumnChart' it throws an error and ColumnCharts are what I'm using. When I change mine to 'ScatterChart' there is no difference in behavior: no charts render and no errors are thrown. :-/

**Comment by rakannimer** [comment]
Hey @kkerley, 

I can't help you with your npm installation problem as it could be a number of things.

Here's [another example of a DiffChart with a ColumnChart](https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/diff-column-chart) with version `2.0.21`.

Cheers
