### ISSUE TITLE
Use of React.Fragment requires React 16

### ISSUE THREAD

**Issue by bekriebel** [rakannimer/react-google-charts#221]
Since a Fragment is introduced, the minimum required version of React is now 16. If this is desired, feel free to close the issue. If you still intend to support this on React 15, the this code causes errors to be produced:

https://github.com/rakannimer/react-google-charts/blob/1c5d9c21fef0ee2e4edf3c1624e85afbc5f38729/src/ReactGoogleCharts.tsx#L436-L452

Unfortunately, I'm stuck on 15 for a bit longer. I can continue to use an older version of this if needed, but I wanted to make sure this was an intended consequence.

**Comment by rakannimer** [comment]
Hey @bekriebel,

Thanks for reporting this ! I actually don't need the fragment. 

I removed them and published as `2.0.22`

**Comment by bekriebel** [comment]
Thanks for the quick turnaround! I'll test it out with the new version on Monday.
