### ISSUE TITLE
Options passed to chart does not work

### ISSUE THREAD

**Issue by orian** [rakannimer/react-google-charts#227]
I've tried both locally and at codesandbox: 
https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/material-line-chart

You can check that the title, legend and curveType are not taken into the account when rendering a chart.

**Comment by rakannimer** [comment]
Yeah the options object passed in this example is not compatible with material chart options (will push a fix to sandbox soon)

To get it to work replace Line with LineChart in chartType, and if you want to use the material design then you need to check the expected options object for it in the google charts docs. (Can't link at the moment)

**Comment by orian** [comment]
Google Charts doc: https://developers.google.com/chart/interactive/docs/gallery/linechart#creating-material-line-charts

```
var options = {
        chart: {
          title: 'Box Office Earnings in First Two Weeks of Opening',
          subtitle: 'in millions of dollars (USD)'
        },
        width: 900,
        height: 500
      };
```

**Comment by rakannimer** [comment]
Thanks @orian for the link ! I'm updating the docs now.

Cheers !
