### ISSUE TITLE
Customized tooltips on scatter plot not working

### ISSUE THREAD

**Issue by djkashtan** [RakanNimer/react-google-charts#23]
I have been able to get them to work outside of react-google-charts, see http://jsfiddle.net/4THAe/1/

I have been stumped by this error while using react-google-charts: "All series on a given axis must be of the same data type". Can you confirm that you can get tooltips working on scatter plots with react-google-charts?

Here is my code, it is as basic as possible:

```
function build_scatter() {
return {rows: [[0.5, 0.5, 'test123']], columns: [{
	    type: 'number',
			role: 'domain',
			label:'Overall Score'
	  },
	  {
	    type: 'number',
			role: 'data',
	    label:'QB'
	  },
		{
	    type: 'string',
			role: 'tooltip',
	    label: null
	  }
	]};
}
```

and then for my plot:

```
var ScatterChartData =
{
    circle_scatter:
    {
      rows : circle_scatter_data.rows,
      columns : circle_scatter_data.columns,
      options:
      {
        title: 'Overall Score vs. Position',
        legend: {bottom: 'top', textStyle: {color: 'black', fontSize: 12}},
        colors: ['#0000FF','#FF0000', '#00FF00'],
        pointSize: 2,
        vAxis: {title: 'Overall Score'},
      }
    }
};
```

**Comment by RakanNimer** [comment]
Hey, 

In the version of the package you were using the role attribute in column was not supported. 
It should work now :)

Cheers

**Comment by djkashtan** [comment]
awesome thanks!

On Wed, Mar 23, 2016 at 7:02 AM, Rakan Nimer <notifications@github.com>
wrote:

> Hey,
>
> In the version of the package you were using the role attribute in column
> was not supported.
> It should work now :)
>
> Cheers
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/RakanNimer/react-google-charts/issues/23#issuecomment-200297356>
>



-- 
-Daniel
