### ISSUE TITLE
Issue with TypeScript definitions

### ISSUE THREAD

**Issue by dsueltenfuss** [rakannimer/react-google-charts#232]
When trying to include this package, I am getting a number of errors, from what appears to be references to a directory on the developers machine

in ReactGoogleChart.d.ts, multiple lines have this'"../../../../../../../../Users/rn/Code/github/active-repos/maintainer/react-google-charts/src/types").GoogleDataTableCell[][] | null'

**Comment by rakannimer** [comment]
Hey @dsueltenfuss,

Thanks for reporting this issue ! 
It was a problem with an older version of typescript I was using. Fixed by updating to latest typescript version. 

It should be solved on your side in version `3.0.4`.

Cheers !
