### ISSUE TITLE
Timeline doesn't take options into consideration

### ISSUE THREAD

**Issue by danielmulvad** [rakannimer/react-google-charts#233]
const options = {
  allowHtml: true,
  legend: {bottom: 'top', textStyle: {color: 'red', fontSize: 24}},
  timeline: {
      groupByRowLabel: true,
}
.....
        <Chart
          chartType="Timeline"
          data={[columns, ...rows]}
          options={options}
          width="100%"
          height="500px"
          legendToggle
          />

<img width="910" alt="screen shot 2018-08-14 at 8 23 56 am" src="https://user-images.githubusercontent.com/41206112/44101126-90aa5ec8-9f9b-11e8-977c-09c6b11aaba9.png">

**Comment by rakannimer** [comment]
Hey @danielmulvad,

It's hard to help you debug this without more info.

Can you try to create a minimal reproduction of the problem ?

Cheers !

**Comment by danielmulvad** [comment]
https://codesandbox.io/s/534j3qwo7n

html doesn't display & no legend
tooltip (dev):
` 'ID: ' + data.hits[i].id + ' Name: ' + data.hits[i].name + ' Operation: ' + data.hits[i].operation + ' Duration: ' + moment((data.hits[i].start + data.hits[i].duration) - data.hits[i].start) / 1000000 + 'ms', `

**Comment by rakannimer** [comment]
Awesome ! 

So the issue is that you need to add an additional property to the tooltip column : 

```
{ type: "string", role: "tooltip", p: { html: true } },
```

Here's a working [sandbox](https://codesandbox.io/s/6jjlknolnn)

**Comment by rakannimer** [comment]
Also, regarding the legend I'm not sure the Timeline chart supports legends. 

Check out [timeline interactive-demo](https://react-google-charts.com/timeline-chart) to see examples of the things you can do.

**Comment by danielmulvad** [comment]
Thanks a lot! I also have another issue with the chart breaking when the data gets too small. Should I make another issue?
(when time is less than 850ms (tested) apart it breaks)

**Comment by rakannimer** [comment]
No need for another issue, can you also provide a minimal repro ?

Cheers

**Comment by danielmulvad** [comment]
https://codesandbox.io/s/534j3qwo7n
timestamp is given in milliseconds ( check here: https://www.epochconverter.com/ )
 ### How to break:
* Under test 2: Changing 850ms -> 849ms
* Removing test 2


it seems having a time difference of less than 850ms will break the chart because it can't "see" between 1 and 0 seconds.

**Comment by rakannimer** [comment]
Interesting 🤔 !

I can't think of why honestly, looks like a limitation from Google Charts.

**Comment by rakannimer** [comment]
Check this : https://codesandbox.io/s/6lqrv817z3

If you change it to different dates (but same interval) it works.
