### ISSUE TITLE
>V2.0.x Issue with Mobx Observable Arrays

### ISSUE THREAD

**Issue by preludeofme** [rakannimer/react-google-charts#235]
I know you can't account for all various state management packages, but just something i found when using Mobx and Observable Arrays, with the latest method for loading the data (using data instead of "columns" and "rows") you have to flatten the observable array for it to work. Otherwise you run into issues with the array being read properly. 

so this:
data={projectState.timelineRows}
needs to be:
data={projectState.timelineRows.slice()}

the ".slice()" flattens the array and fixes the issues. this is more for anyone else running into the issue than something to fix.

**Comment by rakannimer** [comment]
Hey @preludeofme, 

Thanks for reporting this, for future readers !

That makes sense to me, the Chart component only does a shallow check to see if the data has changed ( `prevProps.data !== props.data` ). 

With Mobx Observable Arrays the reference to the observable array doesn't change so `prevProps.data !== props.data` is always false. 

By calling `slice` on the array you're creating a new array from the Observable one which causes it to re-render (`prevProps.data !== props.data` becomes false)

Cheers !
