### ISSUE TITLE
>3.0 issue: Relative height (100%) is ignored, chart displayed with 200px height instead

### ISSUE THREAD

**Issue by Q-Man** [rakannimer/react-google-charts#237]
Until version 2.0.29 it was possible to specify a relative height (like "100%") as property of the <Chart/> component. Since 3.0.x only pixel heights are processed correctly. Relative heights are ignored and resulting in a 200px fixed height of the rendered chart.

Here an example of the resulting HTML for this react code: 

	<div style={{width: "100%", height: "100%"}}>
		<Chart
			chartType="PieChart"
			data={[["", ""], ["Test", 100]]}
			width="100%"
			height="100%"
		/>
	</div>

Resulting HTML in Version 2.0.29 (742px is the correct available height):

	<div style="width: 100%; height: 100%;">
		<div id="reactgooglegraph-1" class="" style="height: 100%; width: 100%;">
			<div style="position: relative;">
				<div dir="ltr" style="position: relative; width: 1280px; height: 742px;">
	...

Resulting HTML in Version 3.0.5 (200px is not the correct available height, should be 742 px):

	<div style="width: 100%; height: 100%;">
		<div>
			<div>
				<div id="reactgooglegraph-6" class="" style="height: 100%; width: 100%;">
					<div style="position: relative;"><div dir="ltr" style="position: relative; width: 1280px; height: 200px;">
	...

**Comment by rakannimer** [comment]
Should be fixed in `3.0.6` !

**Comment by tylervick** [comment]
Hey @rakannimer I think I'm seeing this issue as of `3.0.8`. I have this implemented as following:
```
      <Chart
        chartType="Timeline"
        data={timeline}
        options={options}
        width="100%"
        height="50%"
      />
```

But the tag still renders with 200px
```<div dir="ltr" style="position: relative; width: 1140px; height: 200px;">```

**Comment by Q-Man** [comment]
For me it's working since 3.0.6, also in 3.0.8

**Comment by orian** [comment]
Experiencing this in 3.0.10.

```
const CountByDate = ({ data, isLoading, error }) => {
    const options = {
        legend: { position: 'none' },
        noDataPattern: {
            backgroundColor: '#9f9f9f',
            color: '#eaeaea'
        }
    };

    if (error) {
        console.error(error);
        return null;
    }

    if (isLoading || !data) {
        return <div>Loading data for "{options.title}"</div>;
    }

    return <Chart
        chartType="Calendar"
        width={"100%"}
        loader={<div>Loading Chart</div>}
        data={data}
        options={options}
        graphID = {"CountByDate"}
    />;
};

withFetching(config.get('api') + 'CountByDate')(CountByDate);
```

**Comment by jejesh26** [comment]
hi, same issue in "react-google-charts": "^3.0.10",

**Comment by frisky5** [comment]
hi, same with "react-google-charts": "^3.0.15" Gantt Chart

**Comment by ledo01** [comment]
hi, same issue with "react-google-charts": "^3.0.15" for Timeline chart

**Comment by moecre** [comment]
Hey, same issue here with "react-google-charts": "^3.0.15" for Timeline chart. Is there a solution or workaround?

**Comment by laixintao** [comment]
It happens for me at "3.0.15", I revert it back to using "3.0.6" it works. :)

**Comment by asnurinsyahirah** [comment]
Hi, I'm experiencing the same issue with "react-google-charts": "^3.0.15" for the pie chart. I've reverted the version to 3.0.6 and 3.0.8, but the issue still persists.
