### ISSUE TITLE
Do you have support for multi language?

### ISSUE THREAD

**Issue by hongduclam** [rakannimer/react-google-charts#238]

**Comment by rakannimer** [comment]
Hey @hongduclam 

Yep, you can set the language you want by using the `chartLanguage` prop. 

It should be a 2 letter locale or country code.

**Comment by hongduclam** [comment]
Ok thanks

**Comment by DanyalKhawaja** [comment]
I am using them for Arabic, how do I render them RTL. Thanx in advance.

**Comment by JiaXingKing** [comment]
I'm using chinese.However, 'ch' does not work. the words are still 'en' which is default language.

**Comment by rkazakov** [comment]
I am working with Word Tree chart and chartLanguage prop does not change the locale for me either.
