### ISSUE TITLE
Error: Cannot load different versions of Google Charts.

### ISSUE THREAD

**Issue by MmtBkn** [rakannimer/react-google-charts#239]
Hello,

When I change the language, libaray trows an error.

            <Chart
              key={language}
              chartLanguage={language}
              options={chartOptions}
              width={"100%"}
              chartType={"LineChart"}
              data={[
                [
                  messages["ProductHistory.date"],
                  messages["ProductHistory.reviews"]
                ],
                ...reviews
              ]}
            />

Error that I'm getting:

loader.js:239 Uncaught (in promise) Error: Cannot load different versions of Google Charts.
    at Object.google.l.m.s.Yl (loader.js:239)
    at Object.google.l.m.s.Dl (loader.js:241)
    at google.l.m.s.load (loader.js:243)
    at Object.google.G.H.T.yh (loader.js:224)
    at loader.js:225

**Comment by md-fid** [comment]
Hey @rakannimer,

do you know any solution for this at these days? We have the same issue now, changing the language in React (Redux Interactor) results in a re-rendering of all components including the chart; but then we also get this error message and the chart isn't rendered.

Maybe you can re-open this issue?
Thanks a lot!

**Comment by rakannimer** [comment]
Hey @md-fid, you're right this is still a pending issue ( stupid bot :D ).

Could you please provide me with a simple way to reproduce this so I can start working on fixing it ?

Thanks !

**Comment by rakannimer** [comment]
This looks like a limitation from the google api loader : https://developers.google.com/chart/interactive/docs/basic_load_libs#loadwithlocale

I don't think it's possible to dynamically load a new locale as the loader can only be called once. I might be wrong, but I'm not sure it's possible to fix that from this library's code.

If anyone has ideas, let me know !

**Comment by MmtBkn** [comment]
Sorry, I missed your question.

We couldnt solve the problem and mived forward with another charting libarary which supports multiple locales. 

I still wonder if we can remove and re load all google libarary as a work around.

**Comment by wilhei** [comment]
Hi,

we have the same problem. We have in JSF a button to switch the language. Clicking that button makes an AJAX and refreshes the page. An EL-Expression is used to set the language in the `load` method:
`google.charts.load('current', {packages: ['corechart', 'line'], 'language': #{bean.getLanguage()}});`.

No problem so far. If I open the page in different languages, everything works fine. But if I switch the language by clicking the button, the same error accours and the chart is not rendered.

Is there any solution or workaround for this issue?
