### ISSUE TITLE
Typo in examples

### ISSUE THREAD

**Issue by mqklin** [RakanNimer/react-google-charts#24]
In file `examples/src/components/Examples/BarCharts.js` here is a typo: `var BarChartData = require('../../sample_data/Bar`**c**`hart');` (expect `BarChart`)

**Comment by bIgBV** [comment]
@mqklin why  don't you make a PR with the change ? :)

**Comment by mqklin** [comment]
@bIgBV, because I'm not going to use this library :)

**Comment by bIgBV** [comment]
Fair enough, :+1:

**Comment by RakanNimer** [comment]
Thanks for reporting, fixed :)
