### ISSUE TITLE
Annotate a scatter graph point

### ISSUE THREAD

**Issue by moaiii** [rakannimer/react-google-charts#243]
Hi, Is there a way to annotate the points on a scatter graph? Instead of a tooltip I want to display specific text on top of the circle. 
Many thanks,
 Chris

**Comment by moaiii** [comment]
Thanks @rakannimer for the quick response and example, is there any way to keep the tooltips open without having to hover over them?

**Comment by rakannimer** [comment]
Oh ok, I'm not sure tooltips are your best option then.

I think you're looking for `annotation` and `annotationText`. 

Here's an example that does that : https://codesandbox.io/s/1472v0zrk4

and some code (for the future busy reader 😄): 

```jsx
<Chart
  width={"100%"}
  height={350}
  chartType="ScatterChart"
  loader={<div>Loading Chart</div>}
  data={[
    // Note the third column definition
    [
      "x",
      "y",
      { role: "annotation", type: "string" },
      { role: "annotationText", type: "string", p: { html: true } }
    ],
    [
      0,
      0,
      "something about point 0",
      "<h2> Anything can go here </h2>"
    ],
    [2, 1, "dsa", `<div class="some-class-name">asda</div>`],
    [4, 3, "dsasdsa", "asda"]
  ]}
  options={{
    // This must be also set to render the tooltip with html (vs svg)
    tooltip: { isHtml: true }
  }}
/>
```

Does that help ? 

Cheers !

**Comment by rakannimer** [comment]
You're welcome, Happy to hear that :) 

Cheers !
