### ISSUE TITLE
[3.0.8] regionClick event is not being fired

### ISSUE THREAD

**Issue by Lotti** [rakannimer/react-google-charts#244]
react@16.5.0
react-google-charts@3.0.8

regionClick event is not being fired :\

```
chartEvents = [
        {
            eventName: 'regionClick',
            callback(chartWrapper, googleViz, selected) {
                console.log('Region selected ', selected.region);
            }
        }
    ];
```

```
<Chart graph_id="geoChart"
                                   chartType="GeoChart"
                                   rows={this.mapData()}
                                   columns={this.geoColumns}
                                   options={this.geoOptions}
                                   chartEvents={this.chartEvents}
                                   mapsApiKey="xxxxxxxxx"
                                   width="400"
                                   height="230"
                                   legend_toggle />
```

No problems with "select" event type

**Comment by Falkyouall** [comment]
Hy @rakannimer, first of all, great work! I cant bring the 'onmouseover' event to live tho, whats going on with that?

Regards, Falk

**Comment by rakannimer** [comment]
Hey @Falkyouall 😅 !

As explained here : https://developers.google.com/chart/interactive/docs/reference#chartwrapper-class

ChartWrapper wraps only a subset of the chart events. To get access to onmouseover events you'd have to listen to the `ready` event and then attach a listener to the chart. 

Here's a sandbox with an example : https://codesandbox.io/s/ko29z78wq7

Hope that helps :)

**Comment by RichMatthews** [comment]
hey @rakannimer I was wondering if `regionClick` is still broken? if so, how do I click on any country to show the selected country? or is it only possible with countries passed in to `data`?
