### ISSUE TITLE
Different icon shapes in geo charts

### ISSUE THREAD

**Issue by Sir-hennihau** [rakannimer/react-google-charts#246]
Hi!
I want to use the **geo chart**.

Is it possible to use different shapes for the icons, like seen here?

https://developers.google.com/chart/interactive/docs/points#fullhtml

Thanks & have a nice day.

**Comment by rakannimer** [comment]
Hey ! 

I don't thing it's possible to set different shapes in GeoCharts. You can set circles and control their size and colors, but beyond that I'm not sure it will be possible. 

Maybe Google Maps will serve you better if you want more control over the markers on your map ?
