### ISSUE TITLE
chartEvents not working/fired for Sankey Diagram

### ISSUE THREAD

**Issue by PhaniKumarAdiraju** [rakannimer/react-google-charts#248]
Based on [Listening to chart events example](https://github.com/rakannimer/react-google-charts#listen-to-chart-events), I was trying to implement the same for Sankey Diagram. But the callback event is never fired. I wonder if there is any other way for callback on select of a particular node in Sankey diagram?  Below is the code that I am using: 

```
import React, { Component } from 'react'
import Chart from 'react-google-charts'

const data = [
  ["From", "To", "Weight"],
  ["A", "X", 5],
  ["A", "Y", 7],
  ["A", "Z", 6],
  ["B", "X", 2],
  ["B", "Y", 9],
  ["B", "Z", 4]
];

const options = {};

const chartEvents = [
  {
    eventName: "select",
    callback(chartWrapper) {
      console.log("Selected ", chartWrapper.getChart().getSelection());
    }
  }
];
class SankeyChart extends Component {
  render() {
    return(
      <div style={{padding: 10}}>
        <Chart
          chartType="Sankey"
          width="600px"
          height="200px"
          data={data}
          chartEvents={chartEvents}
        />
      </div>
    )
  }
}

export default SankeyChart
```

**Comment by indigolain** [comment]
@PhaniKumarAdiraju 
I created a pull request to fix the sample, which might be related to your situation. 
Would this fix your events not firing?
https://github.com/rakannimer/react-google-charts/pull/250

**Comment by rakannimer** [comment]
Thanks @indigolain for clearing that up !

I merged your PR to update the README. 

Hey @PhaniKumarAdiraju,

@indigolain updated the README to reflect the API change.

Please let us know if you're still having problem 

Cheers !

**Comment by rakannimer** [comment]
Yeah to do that you might need to retrieve the DataTable of your chart : 

```
const dataTable = chartWraper.getDataTable();
```

And the use its methods, [documented here](https://developers.google.com/chart/interactive/docs/reference#methods)

For further reference I advise you to check : 

- [ChartWrapper Reference](https://developers.google.com/chart/interactive/docs/reference#methods_4)

- [Chart Reference](https://developers.google.com/chart/interactive/docs/gallery/barchart#methods)

- [DataTable Reference](https://developers.google.com/chart/interactive/docs/reference#methods)

Is that what you're looking for ?

Cheers !

**Comment by PhaniKumarAdiraju** [comment]
Thank you but No, not this. Sorry for being vague in my last comment. I am not sure if my use case is possible with Sankey diagram or not. Let me frame my problem in two questions. 

Question1. Can we add Column Labels to the Sankey diagram? Lets say I have a Sankey diagram like this: 
```
[AP] ----> [AQ] ------> [AR] ------> [AS] 
[BP] ----> [BQ] ------> [BR] ------> [BS] 
[CP] ----> [CQ] ------> [CR] ------> [CS] 
```

Then, Can I add column labels (1,2,3,4) to look like below?  
```
 1               2                   3                  4
[AP] ----> [AQ] ------> [AR] ------> [AS] 
[BP] ----> [BQ] ------> [BR] ------> [BS] 
[CP] ----> [CQ] ------> [CR] ------> [CS] 
```


Question2:  Is there a way to know from which column the node was picked? 
Lets say, I have a sankey diagram like this:

```
 1               2                   3                  4
[AP] ----> [AQ] ------> [AR] ------> [AS] 
[BP] ----> [BQ] ------> [BR] ------> [BS] 
[CP] ----> [CQ] ------> [CR] ------> [CS] 

```
and if I click on Node BR,  currently the event gives me only "BR", which is the name of the node. Is there a way to output it is from 3rd column? 
Another example, if I click on Node CQ node then how to get output of both "CQ" and "Column 2"? 

Cheers!

**Comment by indigolain** [comment]
@PhaniKumarAdiraju 
Glad to hear that it worked partially.
I've created a sandbox for you to check out. I think this will answer your questions!
https://codesandbox.io/s/rw34j2ywy4

Cheers!

**Comment by PhaniKumarAdiraju** [comment]
@indigolain  
That's awesome. Thank you! 🎉
