### ISSUE TITLE
Legend not positioning to bottom with Bar chartType

### ISSUE THREAD

**Issue by sumitramanga** [rakannimer/react-google-charts#249]
When using the Bar chartType the legend does not position to the bottom of the container when defined. This also happens in the sandbox demo.

**Comment by rakannimer** [comment]
Hey @sumitramanga,

Can you share a link to the sandbox so I can help debug ?

Cheers !

**Comment by sumitramanga** [comment]
Here you go: https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/material-bar-chart

All I did was add options={{legend: 'bottom'}} and it didn't do anything. legend: "none" does nothing either.

**Comment by rakannimer** [comment]
Ok, this looks like a Google Charts problem with Material Charts and legend positioning. You can track the progress here : https://github.com/google/google-visualization-issues/issues/1964

You can either use the standard BarChart and position your legend : https://codesandbox.io/s/ovlzqrj3wy

Or if you want to build your own legends and position them around the chart I encourage you to check : https://react-google-charts.com/controls-and-dashboard/custom-dashboard-layout.
