### ISSUE TITLE
Changing chartWrapperParams: view has no effect

### ISSUE THREAD

**Issue by Nebs987** [rakannimer/react-google-charts#251]
On button click I am attempting to change the columns that are shown through a view.
My render code is as follows.
```
<Chart
  chartType='ComboChart'
  chartWrapperParams={{
    view: { columns: this.state.viewColumns }
  }}
  rows={this.props.rows}
  columns={this.props.columns}
  options={this.options(series)}
  chartEvents={this.chartEvents()}
/>
```

I am then changing the viewColumns state to be different columns, but the chart does not actually change, and when I look at the `chartWrapper.getView().columns` value it is still whatever my default value for the state was.

**Comment by rakannimer** [comment]
Hey @Nebs987 

If you want to add remove columns, I suggest doing that by changing columns and rows passed to the Chart. 

In your case I guess you'd have to map the props rows and columns to a state that represents your current view. 

If you want to do imperative manipulation of the Chart then you can grab a reference to the ChartWrapper and do whatever you would like by registering a `ready` event to your chart.

Cheers !
