### ISSUE TITLE
mapsApiKey for Geo Charts

### ISSUE THREAD

**Issue by jrlegrand** [rakannimer/react-google-charts#253]
Is there a way to pass a mapsApiKey to the Chart component?  I'm having trouble loading my GeoChart because it seems to be requiring an API key.

https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings

Thanks!

**Comment by rakannimer** [comment]
Hey @jrlegrand,

You should be able to pass the key using the `mapsApiKey` prop.

Cheers !
