### ISSUE TITLE
Sankey Height doesn't update when set from other component - redux store

### ISSUE THREAD

**Issue by PhaniKumarAdiraju** [rakannimer/react-google-charts#256]
Hi
I am using  react sankey diagram, getting the data from redux store. Based on the data, I am trying to alter the height of Sankey diagram as we receive negative height error when the height is less. 
I am able to pass the Sankeylinks, sankeyHeight from redux store as below: 

```
const { sankeyData } = this.props
.....
<Chart 
 chartType="Sankey"
 height={sankeyData.sankeyHeight}
 loader={<div>Loading Chart</div>}
 data={sankeyData.sankeyLinks}
 options={options}
 chartEvents={this.chartEvents}
 />
```

There are two ways to generate this Sankey diagram

1. When clicked on a particular node, this.chartEvents will be called to re-generate the Sankey diagram based on the selected node. 
 2. Using an input box to search for a particular field and generate or re-generate the Sankey diagram.

> Based on the data that I receive, I do this height calculation: 
```
var sankeyHeight = "600px"
  if(max>0 && max<=15){  // max is maximum number of nodes compared in all columns 
    sankeyHeight = "600px"
  } else if(max>15 && max<=40){
    sankeyHeight = "750px"
  } else if(max>40 && max<=110){
    sankeyHeight = "1100px"
  } else {
    sankeyHeight = "huge" // I wont display the diagram but show an alert message
  }
```

- Click on a particular node (this is in same component): 
In this case, I alter the height based on the redux store data from chartEvents that is generated when clicked on a particular node. The chart loads properly with height and data. 

- Using an input box (this is a different component that updates the redux store)
In this case, I do the same like alter the height based on redux store data from input box search. The height and data are passed to the redux store and then accessed by the sankey chart. Sankey loads the data (I can see the change) but the height is not altered. It still will be in the previous state height, which is causing an issue of displaying properly. But in the previous case(option 1), the height changes as well 

Issue: I can see that height is sent to redux store in both cases. But only in Option 1, sankey is updating height and data but in Option 2, Sankey is updating only data.  How to solve this issue? Is there a way to overwrite chart.draw() ? or what do you suggest? 

Thanks. Let me know if you need more info

**Comment by rakannimer** [comment]
Hey !

Can you try moving the height to inside the options object and let me know if it works ? 

```javascript

<Chart 
 chartType="Sankey"
 loader={<div>Loading Chart</div>}
 data={sankeyData.sankeyLinks}
 options={{...options, height: sankeyData.sankeyHeight}}
 chartEvents={this.chartEvents}
 />
```

Will try to reproduce later today.

Cheers !

**Comment by PhaniKumarAdiraju** [comment]
> Hey !
> 
> Can you try moving the height to inside the options object and let me know if it works ?
> 
> ```js
> <Chart 
>  chartType="Sankey"
>  loader={<div>Loading Chart</div>}
>  data={sankeyData.sankeyLinks}
>  options={{...options, height: sankeyData.sankeyHeight}}
>  chartEvents={this.chartEvents}
>  />
> ```
> 
> Will try to reproduce later today.
> 
> Cheers !

Nope! It didn't update height in the Sankey diagram.

**Comment by rakannimer** [comment]
Looks like sankeyData is not being updated when you're changing the height : 

Here's a sandbox with a Sankey that changes height : https://codesandbox.io/s/3r9q0jzl7m

Is that what you're looking for ?
