### ISSUE TITLE
How to disable all events on chart?

### ISSUE THREAD

**Issue by tresdosdos** [rakannimer/react-google-charts#258]
I have to use PieChart with react-swipeable-views, where one of all views is view with PieChart. So when I'm trying to swipe on next or previous view, its trigger PieChart, not my views, and there isn't any swipe in views. How to disable all mouse events from PieChart?

```
<Chart
        chartType="PieChart"
        data={data}
        options={pieOptions}
        graph_id="PieChart"
        width="100%"
        height="400px"
        legend_toggle
      />
```

**Comment by rakannimer** [comment]
Hey @tresdosdos,

You can do that by setting `enableInteractivity` to `false` in pieOptions. This will disable all mouse events.

Here's an example of a chart that doesn't react to mouseEvents : https://codesandbox.io/s/n96qo026wm

Hope that helps,

Cheers !

**Comment by chengzh2008** [comment]
Seems this won't work with treeMap. Is there a way to disable the default move down to leafNode when click node. 

Thanks
