### ISSUE TITLE
Cannot use Dates for minValue and maxValue of hAxis

### ISSUE THREAD

**Issue by andreas-eberle** [rakannimer/react-google-charts#259]
The types of `hAxis.minValue` and `hAxis.maxValue` as well as `hAxis.viewWindow.min` and `hAxis.viewWindow.max` in the chart options are limited to numbers. However, it seems that the original library also accepts dates here. Otherwise, it wouldn't be possible to specify these values for charts with time series data.

**Comment by rakannimer** [comment]
Hey @andreas-eberle,

Thanks for catching this issue ! 

Should be fixed in 3.0.9 

Cheers !
