### ISSUE TITLE
Document is not defined error

### ISSUE THREAD

**Issue by super-cache-money** [RakanNimer/react-google-charts#26]
I'm getting the following error:

    ReferenceError: document is not defined
    [1]     at /my/project/node_modules/scriptjs/dist/script.js:12:13
    [1]     at doc (/my/project/node_modules/scriptjs/dist/script.js:8:72)

In case you need some context, I'm using it within [this boilerplate](https://github.com/erikras/react-redux-universal-hot-example).

Evidently something is wrong because `document` is not defined on the server. Is this `scriptjs`'s fault? Any quick fixes?

**Comment by RakanNimer** [comment]
Looks like it's the latest's release's problem. You can use version 0.1.9 which depends on jQuery for a quick fix while I find the time to check it out ! Should be easy to fix.

```bash
npm uninstall react-google-charts
npm install react-google-charts@0.1.9
```
Thanks for reporting,
Cheers

**Comment by dmmalam** [comment]
+1

**Comment by olalonde** [comment]
Temporary fix which should work with https://github.com/erikras/react-redux-universal-hot-example:

```
const Chart = __CLIENT__ ? require('react-google-charts').Chart : null
```

**Comment by RakanNimer** [comment]
Thanks for reporting !
Should be fixed in 1.0.0 
Let me know if it still breaks

**Comment by mychaelgo** [comment]
@RakanNimer still breaks in 1.0.0

**Comment by iagomr** [comment]
@RakanNimer having the same issue with 1.0.2

**Comment by justinbc820** [comment]
@RakanNimer This issue needs to be reopened.  I'm having this issue with 1.0.2. Also, when I tried to revert back to 0.1.9, I then get the "rendering with a blank div issue"[32](https://github.com/RakanNimer/react-google-charts/issues/32)
