### ISSUE TITLE
Call of getImageURI() for chart 

### ISSUE THREAD

**Issue by md-fid** [rakannimer/react-google-charts#261]
Like in the original Google Charts, what is the way to call the `getImageURI()` function to print PNG images from the chart?
See: https://developers.google.com/chart/interactive/docs/printing

Update: I'm drawing a `Timeline` chart, what is not an `OrgChart` (which does not have the `getImageURI` method on the Chart) in my eyes.

Thanks!

**Comment by rakannimer** [comment]
Hey @md-fid,

I'm not sure it's possible with Timelines :( 

To get access to getImageURI(), you need to register a ready event and then use get the chart from there ! 

```jsx
<Chart 
	chartEvents={{
    eventName: "select",
    callback({ chartWrapper }) {
	  const chart = chartWrapper.getChart()
      // You can use chart now !
    }
  }}
/>
```

Hope that helps ? 

Cheers !
