### ISSUE TITLE
Example of listening to the onmouseover and onmouseout events?

### ISSUE THREAD

**Issue by gyoung-panopto** [rakannimer/react-google-charts#263]
Could you provide an example for how to listen to the onmouseover and onmouseout events?

I am using TypeScript and when I follow the example for the "select" event it says "onmouseover" is not a valid GoogleVizEventName. I'm also wondering how to get the row and column fields from the callback. An example would be greatly appreciated!

**Comment by rakannimer** [comment]
Hey @gyoung-panopto 

onmouseover and onmouseout are chart specific events and are not handled by the Chart component which is a wrapper around Google's ChartWrapper class.

However you can easily use them by grabbing the chart once it's ready, as requested here's an example in a sandbox : https://codesandbox.io/s/ko29z78wq7

And some code : 

```jsx
<Chart
  chartType="ScatterChart"
  width="80%"
  height="400px"
  data={data}
  options={options}
  legendToggle
  chartEvents={[
    {
      eventName: "ready",
      callback: ({ chartWrapper, google }) => {
        const chart = chartWrapper.getChart();
        google.visualization.events.addListener(chart, "onmouseover", e => {
          const { row, column } = e;
          console.warn("MOUSE OVER ", { row, column });
        });
        google.visualization.events.addListener(chart, "onmouseout", e => {
          const { row, column } = e;
          console.warn("MOUSE OUT ", { row, column });
        });
      }
    }
  ]}
/>
```

Hope that helps ? 

Cheers !

**Comment by gyoung-panopto** [comment]
Perfect, thanks!

**Comment by bhavya250198** [comment]
> Hey @gyoung-panopto
> 
> onmouseover and onmouseout are chart specific events and are not handled by the Chart component which is a wrapper around Google's ChartWrapper class.
> 
> However you can easily use them by grabbing the chart once it's ready, as requested here's an example in a sandbox : https://codesandbox.io/s/ko29z78wq7
> 
> And some code :
> 
> ```js-jsx
> <Chart
>   chartType="ScatterChart"
>   width="80%"
>   height="400px"
>   data={data}
>   options={options}
>   legendToggle
>   chartEvents={[
>     {
>       eventName: "ready",
>       callback: ({ chartWrapper, google }) => {
>         const chart = chartWrapper.getChart();
>         google.visualization.events.addListener(chart, "onmouseover", e => {
>           const { row, column } = e;
>           console.warn("MOUSE OVER ", { row, column });
>         });
>         google.visualization.events.addListener(chart, "onmouseout", e => {
>           const { row, column } = e;
>           console.warn("MOUSE OUT ", { row, column });
>         });
>       }
>     }
>   ]}
> />
> ```
> 
> Hope that helps ?
> 
> Cheers !

hi, I  am using React-google how do you highlight the bar on selecting and how do you reset the selected event in react-google charts?

**Comment by coding-Alice** [comment]
Hello, I have tried the example on my TypeScript code, and it's keep throwing error. I'm keep getting Argument of type '{ removeAction: (actionID: string) => void; getSelection: () => { row?: any; column?: any; }[]; setAction: (ChartAction: GoogleChartAction) => void; getImageURI: () => void; clearChart: () => void; }' is not assignable to parameter of type 'GoogleChartWrapper | GoogleChartControl | GoogleChartEditor'.
  Type '{ removeAction: (actionID: string) => void; getSelection: () => { row?: any; column?: any; }[]; setAction: (ChartAction: GoogleChartAction) => void; getImageURI: () => void; clearChart: () => void; }' is missing the following properties from type 'GoogleChartWrapper': draw, toJSON, clone, 

Has anyone solved this error?

**Comment by rpsahani001** [comment]
How to get an error message that unable to show data some problem?

![image](https://user-images.githubusercontent.com/117733754/219534481-31c054f5-44a2-45d8-befe-53e0c309fe4d.png)
