### ISSUE TITLE
Range filters not rendering with charts

### ISSUE THREAD

**Issue by ruffcorn33** [rakannimer/react-google-charts#264]
I am trying to add a date range or chart range slider to a timeline chart.  I am following your example for the line chart at [here](https://react-google-charts.com/controls-and-dashboard/chart-range-filter-control).  I have also followed your example for a date range filter and a table chart.  To test to see if I could get one of your examples to work in my project, I copy/pasted the bar chart/ numeric filter code into my component.  The result is that the chart renders as expected but the filter slider does not.  I see that someone asked a similar question on [StackOverflow](https://stackoverflow.com/questions/53160843/date-range-slider-not-getting-rendered-in-react-google-charts) last week.  I am writing to ask if something has recently changed in the code to affect this or if I may be making the same mistake that the user on SO did?  Thanks.

**Comment by rakannimer** [comment]
Hey @ruffcorn33,

Which version of react-google-charts are you using ? 

Chart Ranges work fine with me, but I haven't tried them with Timeline. If you could provide a sandbox or some code I can copy paste into, I'd be happy to try to help ! 

Cheers !

**Comment by ruffcorn33** [comment]
Hi Rakan,

package.json says I am using version 2.

I will copy my entire component here.  I am rather new to React and Google Charts and it shouldn't be up to you to educate me but if you can give me a hint to make this work, you will make me a hero at work.
import React, {Component} from "react";
import { Chart } from "react-google-charts";

class TimelineChart extends Component {
  constructor(props) {
    super({props});
  }
  
  render() {
    return (
      <div>
        <div className="Timeline">
          <Chart
            width="100%"
            height="135px"
            chartType="Timeline"
            loader={<div>Loading Chart</div>}
            data={[this.props.columns, ...this.props.rows]}
            backgroundColor="#fff"
            options={{
              tooltip:{isHtml:true}, 
              hAxis: {title:this.props.label, format: this.props.hAxisFormat},
              filterColumnLabel: 'start',
            }}
            rootProps={{ 'data-testid': '1' }}
            chartPackages={['corechart', 'controls']}
            controls={[
              {
                controlType: 'DateRangeFilter',
                controlId: 'control',
                options: {
                  filterColumnLabel: 'start',
                  controlPosition:"bottom",
                },
              },
            ]}
          />
        </div>
      </div>
    );
  }
}

export default TimelineChart;

Thank you,

Craig

**Comment by ruffcorn33** [comment]
columns are defined like this:
```
    chartColumns:[
      { type: "string", id: "row_label"},
      { type: "string", id: "Items"},
      { type: 'string', role: 'tooltip', 'p': {'html':true}},
      { type: 'string', role: 'style'},
      { type: "datetime", id: "Start"},
      { type: "datetime", id: "End"},
    ],
```
And some sample data would look like this:
```
[
  [
    "Items",
    "Start",
    "<div class=\"tooltip\"><div class=\"ttHeader\">Start of Shift</div></div>",
    "#004DF5",
    "2018-10-19T15:19:33.000Z",
    "2018-10-19T15:19:33.000Z"
  ],
  [
    "Items",
    "pen",
    "<div class=\"tooltip\"><div class=\"ttHeader\">Pen</div><div class=\"ttBody\">00:00:10</div></div>",
    "#FFFFC2",
    "2018-10-19T15:19:33.000Z",
    "2018-10-19T15:19:37.000Z"
  ],
  [
    "Items",
    "pencil",
    "<div class=\"tooltip\"><div class=\"ttHeader\">Pencil</div><div class=\"ttBody\">00:00:10</div></div>",
    "#4286f4",
    "2018-10-19T15:19:37.000Z",
    "2018-10-19T15:19:47.000Z"],
  [
    "Items",
    "eraser",
    "<div class=\"tooltip\"><div class=\"ttHeader\">Eraser</div><div class=\"ttBody\">00:00:43</div></div>",
    "#FFFFC2",
    "2018-10-19T15:19:47.000Z",
    "2018-10-19T15:19:47.000Z"
  ]
]
```

**Comment by rakannimer** [comment]
Oh ok, so I can see 2 problems, chart range filter was not supported in version 2.
And your controls aren't properly refre
You need to start by updating react-google-charts 

```sh
npm install react-google-charts@latest 
```

in your main directory 

Once that's done you need to update your Chart component and pass to the control the index of the column you want to use to filter.

Here's an example : https://codesandbox.io/s/30vnnk7zk5

The code you care about : 

```jsx
<Chart
  chartType="Timeline"
  data={data}
  width="500px"
  height="400px"
  controls={[
    {
      controlType: "DateRangeFilter",
      options: {
        filterColumnIndex: 1
      },
      controlPosition: "bottom"
    }
  ]}
/>;

```

But for some reason it's not ignoring the first row. 

Going to try to see what's up with that ...

Meanwhile, can you give that a try ?

**Comment by ruffcorn33** [comment]
For some reason, the sandbox doesn't like my datetime values.  It errors on that but still renders a filter slider.  In the calling code, I make new Date() from millisecond values for those columns in the data.

After updating to 3.0.10 and formatting my controls as above, I still get no slider.

As you can see, I am dealing with data at the hour-minute-second level.  Do I need to do anything differently to have the control work at the same level?  React-google-charts does all that as expected for the chart and handles the html tooltips and color styling beautifully.

I am not importing ReactDom into my component and at the end I am exporting the component.  Could that be an issue for me?

**Comment by ruffcorn33** [comment]
If you take a look at the [sandbox](https://codesandbox.io/s/30vnnk7zk5) here, you can see that I am getting a timeline chart and a date range filter controller.  I ran my sample data datetime through new Date() again in order for Google Charts to recognize them as dates.  I don't understand why this helps since I created them using new Date().  I added some chart options and control options to format the hAxis and the scrubber's ui format and now I also get a filter control.  I am not sure what I need to do to implement this in my component or if I even need to since my chart is rendering correctly with the datetimes I have- just with no filter control.  
Also, the scrubber I get looks like a duration rather than hours and minutes.

**Comment by ruffcorn33** [comment]
Update - I should have reloaded my editor after updating react-google-charts in my project.  The slider is now appearing with my timeline chart.  Thank you for helping me with this.

**Comment by rakannimer** [comment]
Happy to hear that :) 

Have a good one !
