### ISSUE TITLE
Chart fails to render in IE11

### ISSUE THREAD

**Issue by FJiskra** [rakannimer/react-google-charts#270]
IE11 fails to render Chart component

error: Object doesn't support this action

here:
`  var googleChartWrapper = new google.visualization.ChartWrapper(chartConfig);`
in GoogleChart.prototype.componentDidMount 

google.visualization.ChartWrapper is undefined

How do I please solve this?

**Comment by norama** [comment]
The problem with IE11 is that `ReactGoogleCharts.onLoad()` is called BEFORE google charts are fully loaded. The `window.google` object does not contain the charts yet, but it is propagated to `GoogleChart`.
In the meantime, the google script sets another `google` object in `window` with the fully loaded charts, but it is never propagated to `GoogleChart`.

The solution in the above pull request #286 : in `ReactGoogleCharts.onLoad()` check if the received `google` object contains the necessary charts, if not, wait and periodically check the `window.google` object for the charts. As soon as the object is fully loaded, propagate it to `GoogleChart`. 

Please merge this solution and publilsh a new version with the fix, we need to solve IE11 compatibility in our project and would like to use this component.
