### ISSUE TITLE
How to put additional hAxis data title

### ISSUE THREAD

**Issue by zverexe** [rakannimer/react-google-charts#272]
Hi, I have quetion.
How can I add additional string in the bottom of each column name, for example from this example https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/column-chart I want to add in the bottom of each column titles (Copper Silver Gold Platinum) some text, for example Test. How can I do that?

**Comment by saraztr** [comment]
Hi @zverexe I think by adding options you can do that. Here is a codesandbox link with options added
https://codesandbox.io/s/v8pxy33555
Hope it helps

**Comment by zverexe** [comment]
@saraztr Hello. I need text below each column title, not just one.

**Comment by zverexe** [comment]
[http://joxi.ru/v2960jRT3aBpYA](url)
