### ISSUE TITLE
Ticks does not accept array of object

### ISSUE THREAD

**Issue by parthiv1993** [rakannimer/react-google-charts#279]
current implementations only accept the array of numbers for axis ticks.
According to implementations of google chart, it also supports array of object which is used to rename the ticks
example : 
hAxis: { ticks: [{v:32, f:'thirty two'}, {v:64, f:'sixty four'}] }

Can you please handle ticks props and types

**Comment by parasvora96** [comment]
I am also having same issue. Need to add custom label on hAxis instead of showing values.
ChartWrapperOptions has 'ticks' in hAxis and vAxis but it accept number of arrays.

**Comment by thepolarchimps** [comment]
Hi Folks, 

Can we re-open this? I was about to submit another request but checked stale and noticed this. 

Just needs the type editing.
