### ISSUE TITLE
Chart is not re-drawn when data source changes

### ISSUE THREAD

**Issue by anarchistgeek** [rakannimer/react-google-charts#281]
I have a component which has a line Chart on it. Data of the chart is retrieved via selector from redux store.

But when the underlying data changes, chart is not re-drawn. This was working before and stopped all of a sudden. I recently updated to latest version of react and using 3.0.10 of react-google-chart.

What might be the reason of chart is not re-drawn when underlying data is changed?

Thanks for your help.

**Comment by anarchistgeek** [comment]
Apparently, Upgrading to 16.8.1 introduced this issue and it still persists. I downgraded react version to 16.5.2, and it started to work again.

**Comment by Reggino** [comment]
Same here. Indeed, downgrading react seems like a temporary workaround

**Comment by RALifeCoach** [comment]
I am using react 16.8 hooks. I can't downgrade. Any news on this?

**Comment by rakannimer** [comment]
Hello, could you provide a concise sample repo (or code sandbox) reproducing the problem ?

**Comment by RALifeCoach** [comment]
Not easily. I have data that can be shown by year (x columns) or month (12X columns). The graph width is set depending on the number of columns. I solved it by:
{scale === 'year'
    ? <ChartComponent key={0} />
    :  <ChartComponent key={1} />
}
