### ISSUE TITLE
is there a way to disable move down/up events for treeMap

### ISSUE THREAD

**Issue by chengzh2008** [rakannimer/react-google-charts#282]
I wound like to disable the default event behavior of move down/up the tree level. And would to like add customized event for 'select'. I have tried this, but it won't work. 

                    chartEvents={[
                        {
                            eventName: "ready",
                            callback: (a) => {
                              a.google.visualization.events.removeAllListeners(a.chartWrapper);
                            }
                        }, {
                            eventName: "select",
                            callback: (a) => {
                                const chart = a.chartWrapper.getChart();
                                console.debug("SELECTED: ", chart.getSelection());
                            }
                        }
                    ]} 

Thanks!

**Comment by jota12x** [comment]
If you don't care about hover, then it's possible by css. Set the attribute pointer-events:none for the id of the chart. This sattisfied my use-case but there should be a better solution.
