### ISSUE TITLE
Uncaught Error: one or more fonts could not be loaded.

### ISSUE THREAD

**Issue by PabloSzx** [rakannimer/react-google-charts#284]
![chrome_skauoogvbt](https://user-images.githubusercontent.com/8672915/53306568-79595880-386d-11e9-92c4-bafde27868bb.png)
![code_fzyqwy5676](https://user-images.githubusercontent.com/8672915/53306588-c6d5c580-386d-11e9-9dbb-abf85b2b9c50.png)

When I'm trying to use the scatter chart it simply doesn't show, and the browser gives that error after a while.

And i'm using the same example chart as given in the documentation.

"react": "^16.8.2"
"react-dom": "^16.8.2"
"react-google-charts": "^3.0.10"

**Comment by usman10scorpio** [comment]
it is happening with me too.

![image](https://user-images.githubusercontent.com/12570317/85729173-02a6c680-b712-11ea-9c6b-b7b080440efd.png)
