### ISSUE TITLE
Markers aren't shown on a GeoChart

### ISSUE THREAD

**Issue by brahimmouhamou** [rakannimer/react-google-charts#287]
There is something wrong with rendering markers on a GeoChart.
I'm trying to render the Italy example locally but with no sucess.

Markers are missing from the demo docs too:
https://react-google-charts.com/geo-chart

But are still visible in the docs of Google:
https://developers.google.com/chart/interactive/docs/gallery/geochart

PS: Locally I added a apiKey but it still did not work.

**Comment by brahimmouhamou** [comment]
Used the wrong api key, geocoder api key should be used, not the googlemaps javascript api key.

**Comment by vchambers6** [comment]
Hey! I am trying to use the google GeoChart react component, and I'm having the same issue. What do you mean by "geocoder api key should be used," and how can I solve this problem?
