### ISSUE TITLE
chartType="Bar" ignoring options attribute

### ISSUE THREAD

**Issue by glautervl** [rakannimer/react-google-charts#288]
Hi, 
I'm trying to disable the chart interactivity for chart type "Bar" without success.
```
options={{ enableInteractivity: false }}
```

For the chart type "BarChart" it is working fine, but not for type "Bar"

To reproduce, you can just access the link below, change the chartType from BarChart to Bar and then insert above options.
https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/bar-chart

is it really a issue or am I doing something wrong ?

**Comment by rakannimer** [comment]
Hey @glautervl,

It looks like enableInteractivity is not yet supported with Material charts : https://github.com/google/google-visualization-issues/issues/2143

Cheers !

**Comment by glautervl** [comment]
ouch  :(

btw 
Thanks, @rakannimer

**Comment by glautervl** [comment]
Hi @rakannimer 

I got a column chart working fine disabling the enableInteractivity feature.

The problem is when you access this link: https://react-google-charts.com/column-chart
It says "Same as BarChart" then you get back to bar chart, but on the github readme page you have a sandbox code / link https://github.com/rakannimer/react-google-charts/blob/master/sandboxes/column-chart/index.js where we can see another chart type "ColumnChart" and it works fine with that options.

**Comment by jakesyl** [comment]
@rakannimer, one of the workarounds cited on google/google-visualization-issues#2143 is to use a jquery listener and manually check what's targeted. Would this be possible here?

**Comment by jakesyl** [comment]
This works.
```
    const chartEvents = [
      {
        callback: ({ chartWrapper, google }) => {
          const chart = chartWrapper.getChart();
          chart.container.addEventListener("click", (ev) => console.log(ev))
        },
        eventName: "ready"
      }
    ];

    return (
      <span>
        <Typography variant="subtitle1" className={classes.label}>
          {title}
        </Typography>
        <div className={classes.chartContainer}>
          <Chart
            width={"100%"}
            height={"200px"}
            legendToggle
            chartType={"Bar"}
            loader={<Spinner />}
            data={data}
            chartEvents={chartEvents}
          />
        </div>
      </span>
``

**Comment by angeligareta** [comment]
Is there any way now of adding an options attribute in the chartType Bar? I need to add a vAxis title and it just ignore my options.
