### ISSUE TITLE
Chart Range filter control not re-drawing

### ISSUE THREAD

**Issue by kent-williams** [rakannimer/react-google-charts#294]
Hello,

I'm using the LineChart with range filter as demoed [here](https://react-google-charts.com/controls-and-dashboard/chart-range-filter-control).

I am unable to change the range parameters after the initial render. I have put the controls in state, and attempt to set that state with an altered range at a later point, the main graph re-renders, but nothing changes on the range filter graph. 

This works just fine with regular google charts. My use case is the following: a user adjust the range sliders to select an area, selects a label from a dropdown and clicks a button, and the range sliders automatically shift to the next region of chart and this repeats until the end of the chart is reached. 

Any guidance would be much appreciated!
-Kent

**Comment by rakannimer** [comment]
Hey ! 

Thanks for catching this, the controls were not being updated properly on re-renders.

Can you try using 3.0.12, it should fix the control not re-drawing with the right range. 

Cheers !

**Comment by kent-williams** [comment]
Works! Thank you very much @rakannimer!
