### ISSUE TITLE
Issue with importing types

### ISSUE THREAD

**Issue by SergeyLys** [rakannimer/react-google-charts#297]
Hi, i'm using latest version (react-google-charts@3.0.12) and getting this errors in `node_modules/react-google-charts/dist/ReactGoogleCharts.d.ts`: 
```
/rootProject/node_modules/react-google-charts/dist/ReactGoogleCharts.d.ts
TypeScript error: Cannot find module 'react-google-charts/src/types'.  TS2307

    44 |         }>;
    45 |         data: null;
  > 46 |         rows: import("react-google-charts/src/types").GoogleDataTableCell[][] | null;
       |                      ^
    47 |         columns: import("react-google-charts/src/types").GoogleDataTableColumn[] | null;
    48 |         diffdata: {
    49 |             old: any;
```

It seems these imports `import("react-google-charts/src/types")` should be from `react-google-charts/dist` folder.

**Comment by rakannimer** [comment]
Hey @SergeyLys,

Thanks for catching and reporting that, it should be fixed in 3.0.13

3.0.12 was using an older version of typescript that had a bug with some emitted definitions (https://github.com/Microsoft/TypeScript/issues/25511)

Cheers !
