### ISSUE TITLE
Import {chart} from "react-google-charts" Error

### ISSUE THREAD

**Issue by srednakun** [rakannimer/react-google-charts#299]
I am getting this error when I try to import the charts. I double checked that they were installed and they are located in the node_modules folder. I am using version 3.0.13.

Uncaught TypeError: __webpack_require__.i(...) is not a function
    at Object../node_modules/react-google-charts/dist/index.esm.js

**Comment by sreenandanan** [comment]
I'm also facing the same issue,

**Comment by rakannimer** [comment]
I can't reproduce this issue (locally or on codesandbox), could you please provide a repo with a reproduction of the problem, so I can help debug it ?

**Comment by srednakun** [comment]
I can't give the repo because it is for a company.  Are there any dependencies needed for this package to work? Or any special webpack requirements? If this isn't enough maybe sreenandanan can link their repo?

Here's what I'm importing in the page I was trying to use google-react-charts (I'm using D3 components now)
`//React
import React, { Component } from 'react';
import ReactDOM from 'react-dom';

import axios from 'axios';

//Jquery
import $ from 'jquery';
import config from '../config';

//Imports from semantic ui
import {
    Grid, Divider, Image, Container
} from 'semantic-ui-react';

//Images
import HeaderImage from '../images/header.png';
import FooterImage from '../images/logo_DOTSC_small1.png';

//Styling
import 'semantic-ui-css/semantic.min.css';
import '../index.css';
import '../css/reports-page.css';

import Utilities, {
    PtInput, PtInputShort, PtInputIcon, PtSelect, PtDateInput,
    PtInputConditionTab, PtInputNextToEachOther
} from '../grit-utilities';
import ScrollArea from 'react-scrollbar';

//Use D3 components to create charts.
var d3 = require('d3');
var BarChart = require('react-d3-components').BarChart;`

The error says its coming from line 202 in react-google-charts/dist.index.esm
