### ISSUE TITLE
Initializes incorrectly when rows contain more than two items

### ISSUE THREAD

**Issue by 321zeggy** [RakanNimer/react-google-charts#3]
Initializing using rows and columns only works correctly when rows have a length of two. I'd like to create a stacked column chart, but only the first of the stacked items is showing up in my chart.

**Comment by RakanNimer** [comment]
Hey,
Did you set isStacked to true in the options object ? Please provide a code sample so I can try to help.

**Comment by 321zeggy** [comment]
I actually think I had the wrong version of this project installed. The version I installed with npm didn't match the version on github.
