### ISSUE TITLE
In legend links, last one is not clickable

### ISSUE THREAD

**Issue by vijimurugan** [rakannimer/react-google-charts#305]
Please check the example in this link

https://react-google-charts.com/pie-chart#slice-visibility-threshold

if you hover over "Others" legend it will not highlight the corresponding slice.I am having the same issue. I have a "select" event listener which is not working for the last legend in my list. Please help me to solve this issue.

**Comment by rakannimer** [comment]
https://www.react-google-charts.com/examples/pie-chart
