### ISSUE TITLE
google visualization functions/objects

### ISSUE THREAD

**Issue by marktiu** [rakannimer/react-google-charts#310]
is there a recommended way to call the static functions like **_sum_** & **_group_** in an event?

i'm also trying to create a DataView for the callback event to pivot the data which i'm currently not sure how to do. 

`google.visualization.data.group`
`google.visualization.data.sum`
`google.visualization.DataView`

**Comment by shakedk** [comment]
Any way to work with DataView?

**Comment by marktiu** [comment]
i ended up making my own component to do what i needed to do
