### ISSUE TITLE
Not working in react-native

### ISSUE THREAD

**Issue by 8604205328** [rakannimer/react-google-charts#316]
I am implementing this code in react native but it's not working. it showing 
 error:-- can't find variable : documnet 
![Screen Shot 2019-08-17 at 4 56 46 PM](https://user-images.githubusercontent.com/54207587/63211077-122bab00-c110-11e9-925b-b5246df20851.png)

**Comment by rakannimer** [comment]
Unfortunately it won't work with react-native because it uses Google Charts which works only in browsers.
