### ISSUE TITLE
Unable to toggle chart types

### ISSUE THREAD

**Issue by aaron-origin** [rakannimer/react-google-charts#317]
Hi,

First of all, awesome work so far.

I have found an issue with this library, though i'm sure its more of a tweak then a bug. 

I've been working with both ChartJS (React Wrapper) and HighCharts(React Wrapper). I have been able to toggle chart types with both of them, its a fairly straight forward process. I have a state called chartType and a button that changes it. On your google charts wrapper I am unable to do this.

Please see an example codesandbox:
https://codesandbox.io/s/react-google-chartsbroken-toggle-p9421

This may be a quick fix but i am unable to locate the reason for it not working. Almost like it is not re-rendering.

**Comment by rakannimer** [comment]
Hey,

Thanks for reporting this with a repro ! 

It looks like you're right, it's not re-rendering the chart when the chartType is changed. I'm investigating and will report back here when I fix it.
