### ISSUE TITLE
Cannot render chart from array

### ISSUE THREAD

**Issue by mharrisweb** [RakanNimer/react-google-charts#32]
Hello, 

I am trying to pass data as an array, using the code below. The chart doesn;t appear just a grey box. I don't get any errors, Can you help?

             var chartAttributes = {
                chartType: this.props.chartTypes[this.state.statsChart.chartType],
                graph_id: this.props.chartTypes[this.state.statsChart.chartType],
                width: this.state.statsChart.chartWidth,
                height: this.state.statsChart.chartHeight,
                legend_toggle: true
            };

            chartAttributes.options = {
                title: 'Stats ' + this.props.chartTypes[this.state.statsChart.chartType],
                is3D: this.props.chartTypes[this.state.statsChart.chartType] == 'PieChart'
            };

            chartAttributes.data = [
                ['Attendance','Percentage'],
                ['Present',this.getCodesTotals().present[0]],
                ['Authorised Absent',this.getCodesTotals().authorisedAbsent[0]],
                ['Unauthorised Absent',this.getCodesTotals().unauthorisedAbsent[0]]
            ];

            return (
                <Chart {...chartAttributes} />
            );

**Comment by xinghengwang** [comment]
same here: 

Just white box, nothing renders: here is my code. 
I am using 0.1.9 version because of this issue: (https://github.com/RakanNimer/react-google-charts/issues/26). With 0.1.9 at least no error is produced, but nothing is drawn. 

render() {

    var options = {
      title: 'Age vs. Weight comparison',
      hAxis: {title: 'Age', minValue: 0, maxValue: 15},
      vAxis: {title: 'Weight', minValue: 0, maxValue: 15},
      legend: 'none'
    };

    var data = [
      ['Age', 'Weight'],
      [ 8,      12],
      [ 4,      5.5],
      [ 11,     14],
      [ 4,      5],
      [ 3,      3.5],
      [ 6.5,    7]
    ];

    return ( <Chart
        chartType = "ScatterChart"
        data = {data}
        options = {options}
        graph_id = "ScatterChart"
        width={"100%"}
        height={"400px"}
        legend_toggle={true} />
    );

  }

**Comment by RakanNimer** [comment]
Hey, sorry for the late reply.

This is either related to this https://github.com/RakanNimer/react-google-charts/issues/34
or the input that you're sending to it is wrong. 

I'm closing this issue for now if the error occurs again I'd be happy to help you debug if you can post some code that I can run. 

Cheers,
