### ISSUE TITLE
Is it possible to hide a column via react-google-charts?

### ISSUE THREAD

**Issue by oander11** [rakannimer/react-google-charts#323]
Hi,
first got to say I'm sorry using the issues board to ask a question. It seems it sometimes is used this way so that's why I opted for it. If some other channel is preferred, pls let me know.

Anyway, I just wonder if it is possible to hide columns in a Table Chart per this: [https://stackoverflow.com/questions/8785894/how-to-hide-column-in-google-charts-table](https://stackoverflow.com/questions/8785894/how-to-hide-column-in-google-charts-table)

I do not understand if it is possible to get/manipulate a `google.visualization.DataView` via R-G-C, at least I haven't been able to figure it out.
Thanks
/ola

**Comment by rakannimer** [comment]
Hey @oander11 

If you want the user to toggle visibility by clicking on the legend, check out the `legendToggle` prop.

If you want to do it in response to something different, than the best way would be to remove the column data from the data 2d array you supply to react-google-charts.

**Comment by oander11** [comment]
Thanks, I actually don't want to do it in response to anything, just have some data (id values) which is convenient to have in the table records but should never be visualized. 
I think DataView.setColumn is the goto solution for this in vanilla Google Charts, but it's always possible to solve in other ways of course. ChartWrapper.setView{'columns': [0, 1, 4, 5]} will work so maybe I can do this declaratively via the columns prop... or if nothing else, jsut hide it via css :-)

**Comment by hardith** [comment]
@oander11 you can use the "chartWrapperParams={{ view: { columns: [0, 3] } }}" property to hide any specific column, you can refer to the example in this url https://react-google-charts.com/controls-and-dashboard/category-filter-control.

**Comment by xhairaf** [comment]
> @oander11 you can use the "chartWrapperParams={{ view: { columns: [0, 3] } }}" property to hide any specific column, you can refer to the example in this url https://react-google-charts.com/controls-and-dashboard/category-filter-control.

In case someone needs it, the correct url to the example for now is: https://www.react-google-charts.com/examples/advanced-controls#category-filter-control

**Comment by ElielsonU** [comment]
that's the worst library i've ever seen in my life.
