### ISSUE TITLE
ColumnChart Adding Labels Above Each Bar

### ISSUE THREAD

**Issue by isaiahscheel** [rakannimer/react-google-charts#325]
Is there a way to add a label above each bar in a ColumnChart / BarChart? I am trying to display the vAxis value above each bar similar to if you hover over it, but for it to always be there. I'll add what I am trying to replicate. 

![Screen Shot 2019-10-21 at 11 48 43 AM](https://user-images.githubusercontent.com/40191651/67233786-c12e8080-f3f8-11e9-9fe3-b6266a23917e.png)

**Comment by ksondhi** [comment]
@Isaiaher I am trying to do the same thing with a `ColumnChart`.  Were you able to do this?  Thanks.

**Comment by akachida** [comment]
@Isaiaher You can use the { role: 'annotations } with columns labels
You can find it here https://developers-dot-devsite-v2-prod.appspot.com/chart/interactive/docs/gallery/columnchart
