### ISSUE TITLE
HTML in tooltip doesn't work

### ISSUE THREAD

**Issue by Daniel15** [rakannimer/react-google-charts#354]
Google's docs say to add `isHtml: true` under `tooltip`: https://developers.google.com/chart/interactive/docs/customizing_tooltip_content#using-html-tooltips

but that doesn't seem to work with this library

Repro: https://hjwtp.csb.app/
```
<Chart
  options={{
    backgroundColor: "#222",
    tooltip: {
      isHtml: true
    }
  }}
  chartType="GeoChart"
  data={[
    [
      { type: "number", id: "Latitude" },
      { type: "number", id: "Longitude" },
      { type: "string", id: "Location" },
      { type: "string", role: "tooltip" }
    ],
    [
      -37.813733,
      144.964363,
      "Melbourne, Australia",
      "Australia is <b>the best</b>"
    ]
  ]}
  width="100%"
  height="400px"
  legendToggle
/>
```

The raw HTML is still shown:
![image](https://user-images.githubusercontent.com/91933/79625031-e7e51f80-80da-11ea-85b8-b2ce57fc311e.png)

**Comment by justinharkey** [comment]
I know this is several months later but I had the same need and found a solution. You are missing a couple keys in your tooltip entry:

`<Chart
  options={{
    backgroundColor: "#222",
    tooltip: {
      isHtml: true
    }
  }}
  chartType="GeoChart"
  data={[
    [
      { type: "number", id: "Latitude" },
      { type: "number", id: "Longitude" },
      { type: "string", id: "Location" },
      { 'type': 'string', 'role': 'tooltip', 'p': {'html': true} }
    ],
    [
      -37.813733,
      144.964363,
      "Melbourne, Australia",
      "Australia is <b>the best</b>"
    ]
  ]}
  width="100%"
  height="400px"
  legendToggle
/>`

**Comment by Officialstrike** [comment]
@Daniel15 Please close Issue as is it resoloved.

**Comment by Daniel15** [comment]
Thanks for the info!
