### ISSUE TITLE
typescript .d.ts?

### ISSUE THREAD

**Issue by HenrikBechmann** [RakanNimer/react-google-charts#36]
Sorry to ask this here; is there a typescript definition file available for react-google-charts?

**Comment by RakanNimer** [comment]
Hey Henrik,

Unfortunately there isn't but I'd be happy to merge a pull request with one
!

Cheers

**Comment by HenrikBechmann** [comment]
Thanks @RakanNimer For now I've kludged:
```
// react-google-charts.d.ts

declare module 'react-google-charts' {
    var exports: Object;
    export = exports;
}
```

Then in my class file:

```
/// <reference path="../../../typings-custom/react-google-charts.d.ts" />
import * as React from 'react'
import ChartObject = require('react-google-charts')
var { Component } = React

let Chart = ChartObject['Chart']

class Explorer extends Component<any, any> {

    constructor(props) {
        super(props);
        this.state = {
            data: null,
            options: null
        };
    }
...
```
... including the initialization of `state`.

This allows me to render your 'Age vs. weight' test chart.

Nice!

Are there any logical limits to your interface in terms of usage of google charts?

**Comment by RakanNimer** [comment]
There shouldn't be any limits as far I can see , but if you do find one, please let me know so I can remedy it !
