### ISSUE TITLE
avoid listener memory leaks?

### ISSUE THREAD

**Issue by HenrikBechmann** [RakanNimer/react-google-charts#37]
should something like this be added for componentWillUnmount to avoid memory leaks?

http://stackoverflow.com/questions/30657543/google-charts-remove-event-listener

```
var event = google.visualization.events.addListener(chart, 'onmouseover', function() {
    alert('onmouseover');
    google.visualization.events.removeListener(event); //the event object as param
});

```

**Comment by RakanNimer** [comment]
Thanks for the suggestion! I detached all event listeners on componentWillUnmount you can start using it in react-google-charts 1.0.0
