### ISSUE TITLE
Gantt chart not working from both Example and Sandbox

### ISSUE THREAD

**Issue by ropinheiro** [rakannimer/react-google-charts#374]
I'm trying to perform some chart library comparison [here](https://github.com/ropinheiro/LearningReact/tree/master/chart-libs-compare). But I'm struggling in having the Gantt chart working properly.

If you pull that repo, go to the subfolder **chart-libs-compare**, and look at the **React Google Charts** tab, then **scroll down**, you will see: 

![image](https://user-images.githubusercontent.com/19519494/86926184-ad16e480-c129-11ea-82a6-fb904a1cb91d.png)

The code behind that error is an exact copy-paste of the **Styling Arrows** example [here](https://react-google-charts.com/gantt-chart) with some very basic component around (you can see that it doesn't affect the other charts).

I tried to understand what is happening. From this StackOverflow [post](https://stackoverflow.com/questions/43911669/google-chart-cannot-read-property-datefield-of-undefined-for-a-datetime) I noticed that the code in the example have a lot of nulls. I filled all nulls for dates and durations (code not committed). The error persisted, even with a reboot and a cache clean.

Finally, I noticed some code available through Code Sandbox:

https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/gantt-chart?file=/index.js

But even this has some strange bug. First, when entering in the code, I see this error:

![image](https://user-images.githubusercontent.com/19519494/86927019-b2c0fa00-c12a-11ea-9de1-f436bc07687b.png)

I can see the chart at the right, but no image where it should appear:

![image](https://user-images.githubusercontent.com/19519494/86927088-c8362400-c12a-11ea-8cc1-27c96c54b335.png)

But the worse is that if I do **any change** to the code and fork it, say, **add a single space** somewhere, the fork happens, but then the chart no longer appears, instead, an error emerges:

![image](https://user-images.githubusercontent.com/19519494/86927219-f7e52c00-c12a-11ea-930c-fbd088362237.png)

It happens with both Chrome and Firefox.

Is this a know issue? It seems that Gantt chart only works "in your machine" - I see the Gantt chart working in both example page and CodeSandbox (despite that error with the image) but once you move the code somewhere (copy-pasting the example code or forking the CodeSandbox) it no longer works (doesn't work "in my machine").

Thank you!

**Comment by rakannimer** [comment]
Gantt Chart sandboxes and live examples : https://www.react-google-charts.com/examples/gantt
