### ISSUE TITLE
Legend in ColumnChart blinks when animation options is set

### ISSUE THREAD

**Issue by joaopslins** [rakannimer/react-google-charts#387]
Reproducible sandbox:
https://codesandbox.io/s/icy-pine-zxgdl?file=/index.js

Steps to reproduce
- Type something in the `<input>` tag
- See that the Legend disappears for the duration of the animation

Am I doing something wrong or this is a bug?

**Comment by mghanii** [comment]
It's an issue within GC
https://groups.google.com/g/google-chart-api/c/q15ggJ0sHNc

**Comment by rakannimer** [comment]
I guess you could get around that by moving the chart to a separate component and memoizing it to avoid re-renders when the input state changes.
