### ISSUE TITLE
Custom labels for Treemap?

### ISSUE THREAD

**Issue by admc** [rakannimer/react-google-charts#393]
Awesome project. 

Was wondering if it was possible to define my own rendering function for the labels? I have a path, and i'd like to parse it and only show the filename. I'd parse it in the original dataset, but there is a uniqueness problem at the level of depth in the path.

Any ideas?

Thanks so much!

**Comment by rakannimer** [comment]
Thanks !

It seems it's possible https://stackoverflow.com/questions/11714380/google-visualization-treemap-how-to-create-custom-text
