### ISSUE TITLE
support for material design charts?

### ISSUE THREAD

**Issue by stevesuh** [rakannimer/react-google-charts#40]
I think some of the chart options only work with material design.

```
    axes: {
      y: {
        0: {side: 'right'}
      }
    }
```

Here's the fiddle from Google's example.  https://jsfiddle.net/api/post/library/pure/

**Comment by stevesuh** [comment]
Here's a regular bar chart where the axes option doesn't work since it's not material design.

https://jsfiddle.net/3v2xmhqy/

**Comment by fabioml1** [comment]
You can use material with react charts, like this example:
....
<Chart chartType="google.charts.Bar" 
  options = google.charts.Bar.convertOptions(options)
.....
/>

**Comment by stevesuh** [comment]
Yes but this react module does not support the material charts.  It uses ChartWrapper(https://developers.google.com/chart/interactive/docs/reference#chartwrapperobject)  which only support the classic charts.

**Comment by mrn3** [comment]
Would it be difficult to enhance so that it does support material charts (and not just classic ones)?

**Comment by RakanNimer** [comment]
I haven't had time to look into it yet, PRs are very welcome :)

**Comment by mrn3** [comment]
Okay thanks - from what I can see, I don't see many charts in the new material look yet - I think only bar charts.  Perhaps it isn't worth it yet.

**Comment by adambowles** [comment]
Some features aren't available in classic style, like dual axis column charts

https://developers.google.com/chart/interactive/docs/gallery/columnchart#dual-y-charts

**Comment by adambowles** [comment]
It appears (with a cursory look over docs) that the only difference is the chart instantiation method.

Material: `new google.charts.Bar` Classic: `new google.visualization.ColumnChart`
(See: https://jsfiddle.net/mbv0jrf2/)

**Comment by RicardoVaranda** [comment]
Is it currently not possible to use Material with  google.visualization.ChartWrapper ?

**Comment by cavaloni** [comment]
I looked into the code for both of those options and tried to tinker with minimal updates per the document referenced by @adambowles but it seems there needs to be a deeper editing to get it to work.

**Comment by danielmana** [comment]
It looks like just using `chartType="Bar"` makes the trick. google.visualization.ChartWrapper takes the chartType parameter and renders whatever we pass there

**Comment by toolaugh** [comment]
this problems are same to me. React-google chart library now does not support material-chart . Who can help ? ???

**Comment by toolaugh** [comment]
@adambowles  when I using with material chart , I can not stacked colunm ? have you tried ?

**Comment by rakannimer** [comment]
For future reference, material design charts are supported. 

### Material Bar Chart

- [Code](./sandboxes/material-bar-chart/index.js)
- [Sandbox](https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/material-bar-chart)

### Material Line Chart

- [Code](./sandboxes/material-line-chart/index.js)
- [Sandbox](https://codesandbox.io/s/github/rakannimer/react-google-charts/tree/master/sandboxes/material-line-chart)
