### ISSUE TITLE
getCharts() returns null inside "select" event callback

### ISSUE THREAD

**Issue by mefp** [rakannimer/react-google-charts#408]
Hi there. Thanks for the great work. I'm seeing an issue here and have provided a hacky workaround below. I tried to find in the code how this is happening but I couldn't figure it out. I'm not that advanced :\

Here's how I'm using the Chart component:
```
const chartEvents = [{
    eventName: 'select',
    callback: ({ chartWrapper }) => {
      const selection = chartWrapper.getChart().getSelection();
      console.log(selection);
  }];

  return (
    <Chart
      width="100%"
      chartType="GeoChart"
      data={dataArray}
      options={options}
      className={style.map}
      mapsApiKey={Maps[`${'_self' in React.createElement('div') ? 'dev' : 'prod'}_key`]}
      chartEvents={chartEvents}
    />
```

The error I'm getting is: 
```
{{app-0499ae29fa13c04a46c3.js:570 Uncaught TypeError: Cannot read property 'getSelection' of null
at callback (app-0499ae29fa13c04a46c3.js:570)
at vendor-0499ae29fa13c04a46c3.js:1369
at gvjs_H.<anonymous> (jsapi_compiled_default_module.js:166)
at gvjs_ni (jsapi_compiled_default_module.js:165)
at gvjs_H.gvjs_.dispatchEvent (jsapi_compiled_default_module.js:163)
at gvjs_I (jsapi_compiled_default_module.js:165)
at jsapi_compiled_default_module.js:465
at gvjs_H.<anonymous> (jsapi_compiled_default_module.js:166)
at gvjs_ni (jsapi_compiled_default_module.js:165)
at gvjs_H.gvjs_.dispatchEvent (jsapi_compiled_default_module.js:163)}}
```

Am i doing something wrong here? 

Steps taken:

Firstly, I removed the destructuring in the callback:

```
...
callback: ( eventData ) => {
  debugger;
  ...
}
```

The data I'm trying to access has two columns. Column one is a string (country name), and column two is an object with two attributes: lat/long, and an internal data point. I accessed the data like this from the console:

```
eventData.eventArgs[0].getSelection()[0].row                      // => 9587
eventData.chartWrapper.getDataTable().Wf[9587].c[0].v    // => "russia"
eventData.chartWrapper.getDataTable().Wf[9587].c[1].v    // => 25451529.163664438
eventData.chartWrapper.getDataTable().Wf[9587].c[1].f    // => "2543"
```

My hunch is that the chartWrapper's reference to the chart object is not bound correctly....and that may be something I'm doing incorrectly elsewhere in my code. Let me know if you need to see anything else and I'll post it here. 

Thanks!

**Comment by rakannimer** [comment]
This should be fixed : https://www.react-google-charts.com/examples/geo-chart
