### ISSUE TITLE
Script.js dependency breaks Mocha tests

### ISSUE THREAD

**Issue by mlcook2** [RakanNimer/react-google-charts#41]
When I include react-google-charts on a component my mocha tests are breaking: 

```
TypeError: doc.getElementsByTagName is not a function
 at .../node_modules/react-google-charts/node_modules/scriptjs/dist/script.js:13:18
```

The Script.js library appears to expect a document to exist during execution, but that is not the case when running mocha tests.

**Comment by RakanNimer** [comment]
Thank you for reporting !
I added a fix in 1.0.0 to check if document is defined before using script.js. 
Let me know if it still breaks :)
