### ISSUE TITLE
I am not able to show Y axis line for columnChart in react-google-chart 

### ISSUE THREAD

**Issue by supriya-somavnshi** [rakannimer/react-google-charts#459]
I am using columnChart in react google chart (version 3.0.15 ).
On y axis only labels are showing but line is not showing. I did not find any option to show y axis line. Please help me.
![image](https://user-images.githubusercontent.com/73587174/144238761-21c580f6-cb97-44bf-be11-cbf59f3ef9f2.png)

**Comment by rakannimer** [comment]
https://developers.google.com/chart/interactive/docs/gallery/columnchart#configuration-options
