### ISSUE TITLE
Does Timeline chart work?

### ISSUE THREAD

**Issue by hari-rangarajan** [RakanNimer/react-google-charts#47]
I get an error "google.load is not a function". Other charts do seem to work.

**Comment by RakanNimer** [comment]
Yes it should work but you need to set chartPackages prop as  ['timeline'] to load the timeline library from Google Chart API
Try these props : 
```javascript
 {
    chartType: 'Timeline',
    columns: [
      {id: 'President', type: 'string'},
      {id: 'Start', type: 'date'},
      {id: 'End', type: 'date'}
    ],
    rows: [['Washington', new Date(1789, 3, 30), new Date(1797, 2, 4)],
      ['Adams', new Date(1797, 2, 4), new Date(1801, 2, 4)],
      ['Jefferson', new Date(1801, 2, 4), new Date(1809, 2, 4)]],
    width: "100%",
    chartPackages: ['timeline']
  }
```

**Comment by henryshangguan** [comment]
I've tried this, but I'm still getting the "google.load is not a function" error. Any ideas? Thanks!

**Comment by RakanNimer** [comment]
Are you rendering it on the server ? I tested the code I provided on the latest version and it works.

**Comment by dreel** [comment]
I had this problem too, and figured it out. I was mixing non-timeline charts with timeline charts, but the GoogleChartLoader is setup as a singleton that will load the first set of chartPackages you pass in.

So if you only pass `chartPackages={['timeline']}` to the timeline chart but do not pass the `chartPackages` prop to other charts, whichever loads first will work and the others won't.

To fix I just pass `chartPackages={['corechart', 'timeline']}` to all charts (most importantly the first one). It would probably be less confusing if there was an explicit initialization step where you list the packages you will ever use, IMO.

**Comment by RakanNimer** [comment]
Keeping this open until we either add clarification in docs, or fix chartLoader singleton logic.
