### ISSUE TITLE
new chartType blows away events

### ISSUE THREAD

**Issue by HenrikBechmann** [RakanNimer/react-google-charts#49]
It turns out that changing chart type blows away events. I've had to do this inside `drawChart()`:

    ...
    else {
      this.updateDataTable.bind(this)();
      this.wrapper.setDataTable(this.dataTable);
      // this.wrapper.setChartType(this.props.chartType)
      this.wrapper.setOptions(this.props.options)
      if (this.wrapper.getChartType() != this.props.chartType) {
        google.visualization.events.removeAllListeners(this.wrapper)
        this.wrapper.setChartType(this.props.chartType)
        var self = this
        google.visualization.events.addOneTimeListener(this.wrapper, 'ready', function () {
          self.chart = self.wrapper.getChart();
          self.listenToChartEvents.call(self);
        });
      }
    }
    this.wrapper.draw();

**Comment by RakanNimer** [comment]
Yeah that sounds right ! Can you submit a PR with this edit? Would love to add it to the library.

**Comment by nicattisano** [comment]
Are new chart types working? I can only seem to get the scatter chart running.

**Comment by HenrikBechmann** [comment]
here's my forked version of Chart.js (forked from previous version, not current version) fwiw. Sorry I don't have time to do a formal integration and pr.

https://github.com/CivicTechTO/budgetpedia-dev-frontend/blob/master/forked/react-google-charts/Chart.js

**Comment by RakanNimer** [comment]
Can you try now on master branch ? 
Should work.
Cheers :)
