### ISSUE TITLE
Attempting to load version '51' of Google Charts, but the previously loaded 'current' will be used instead. 

### ISSUE THREAD

**Issue by cburkins** [rakannimer/react-google-charts#493]
Use of react-google-charts now seems to be consistently throwing this warning in the console:

Attempting to load version '51' of Google Charts, but the previously loaded 'current' will be used instead. 

You can see a simple example here (open the chrome dev console)

https://codesandbox.io/s/react-google-charts-s31bo?from-embed

And here's a screenshot of same: 

![image](https://user-images.githubusercontent.com/9342308/147366207-5af1183c-6202-40b8-ae13-50ccc0866445.png)

**Comment by eranbetzalel** [comment]
If you just want to ignore it, you can use this code until they'll figure out a fix.

```
const originalWarn = console.warn;

console.warn = function (...args) {
    const arg = args && args[0];

    if (arg && arg.includes('Attempting to load version \'51\' of Google Charts')) return;

    originalWarn(...args);
};
```

FYI, I think they've already fixed it in the Angular version.

https://github.com/FERNman/angular-google-charts/issues/162

**Comment by eranbetzalel** [comment]
FYI, I've just replaced it with [recharts](https://www.npmjs.com/package/recharts), Google Charts has not updated its Material part since 2016 (https://github.com/google/google-visualization-issues/issues/2143).

**Comment by cburkins** [comment]
Thinking about departing google charts too....    also using recharts...   though can't find anyone else with a good gauge chart like google charts, so I guess I'll keep staring at that warning :(

**Comment by eranbetzalel** [comment]
@cburkins, you better use this package than staying with Google Charts deprecated package.

https://codesandbox.io/s/react-d3-gauge-gwebx

**Comment by alynaug** [comment]
Hi. Any substitutes for GeoCharts?

**Comment by Taco-lb** [comment]
I dont know if its too late, but specifying the chartVersion='51' will remove the warning since it is setting it to always render at the version mentioned 

for example in this react code i used the geochart

`<Chart
                    chartType="GeoChart"
                    loader={<Spinner/>}
                    chartVersion='51'
                    data={countryData}
                    options={options}
                    />`

**Comment by jsimpson-www** [comment]
Thank you!  I appreciate you taking the time to respond with helpful information.  Best regards!


JimSimpson
Software Development Manager
400 Metro Place North, Ste. 201
Dublin, OH43017
***@***.***
o: (614) 228-5000
d: (614) 716-0476
 | ext: 21176
m: (614) 353-2735

**Comment by jsimpson-www** [comment]
Thank you, this was very helpful.  Best!
