### ISSUE TITLE
npm install is pulling in a some version of react-google-charts that does not work

### ISSUE THREAD

**Issue by r-tock** [RakanNimer/react-google-charts#5]
I have been trying to figure out which commit it was however it seems to refer to a function `build_big_data_table` which is not shown in the commit history of this git hub repo. I would recommend re-exporting the code to npm.

**Comment by r-tock** [comment]
changing

`"react-google-charts": "^0.1.4",`
to
 `"react-google-charts": "git+ssh://git@github.com/RakanNimer/react-google-charts.git",` 
is making our app work again.

**Comment by RakanNimer** [comment]
Thanks for pointing that out ! I pushed a version I was debugging to npm. Should be fixed now :)
