### ISSUE TITLE
Sanjay diagram support

### ISSUE THREAD

**Issue by Julien042** [RakanNimer/react-google-charts#50]
Hi Rakan,

Thanks for this very helpful piece of work.
Wondered if Sankey diagram was supported or if you had any plan to add it in the near future?

**Comment by Julien042** [comment]
Hi,

Found the answer: To make it work, just need to set  chartPackages={['sankey']} and chartType="Sankey" in the props of the Chart component.

**Comment by RakanNimer** [comment]
Thanks for reporting :) 

Will add a Sankey chart to the demo site as soon as I have some free time :) 

Cheers !
