### ISSUE TITLE
Drawing multiple graphs

### ISSUE THREAD

**Issue by willyyang** [RakanNimer/react-google-charts#54]
Hi there,

Is there a way to create multiple graphs? I can get one graph to render then the second one will be stuck in the `Rendering Chart...` phase.

I have an array of objects that have configurations/options for the graphs then I map this array to a component that calls `<Chart />`.

Am I missing something here to make multiple graphs show up? Thanks!

**Comment by willyyang** [comment]
```
<div>
          <div id='project-margins'>
          {graphs.map(graph => 
            <Chart
              chartType = 'ColumnChart'
              data ={data}
              graph_id = 'ColumnChart'
              width={'100%'}
              height={'400px'}
            />
          )}           
        </div>
      </div>
```

**Comment by RakanNimer** [comment]
Hey,
It looks you're using the same graph_id for the generated graphs.
Either use different ids for each or don't set one and it will
automatically generate graph_ids for you .

Hope that helps,
Cheers !

**Comment by willyyang** [comment]
Doh. Thanks dude!

**Comment by RakanNimer** [comment]
You're welcome :)

**Comment by anylyne** [comment]
I'm having the same issue even if I'm using a unique id for each graph or if I'm letting it generate the id itself. The version I'm using is 2.0.29.

**Comment by rakannimer** [comment]
Hey @anylyne,

Can you try updating to >=3.0 

npm i react-google-charts@latest

and try again ? 

Cheers !

**Comment by anylyne** [comment]
Thank you for your answer, @rakannimer!

My project is using react 15.3.2. Is there any other option in this case?

Best,
Carol.

**Comment by RachelMcNeely** [comment]
Hi @rakannimer,

I am also in the same boat as @anylyne - one chart renders while the others are stuck. However, when I navigate away and then back again, all charts render properly. I also can't update because my project uses React 15.6.2. Is there any other option besides updating >=3.0? Thanks!

**Comment by rakannimer** [comment]
Hey @anylyne & @RachelMcNeely ,

It would be very helpful if you can create a sandbox that reproduces the problem and I can try to help debug there ? 

Cheers !
