### ISSUE TITLE
Disable console log messages

### ISSUE THREAD

**Issue by nicolasiensen** [RakanNimer/react-google-charts#55]
Hey guys,

How can I disable the console logs from the library?

<img width="1269" alt="screen shot 2016-06-22 at 1 26 03 pm" src="https://cloud.githubusercontent.com/assets/208312/16264946/f67b659a-387c-11e6-8ce5-2ea851cbdd31.png">

**Comment by RakanNimer** [comment]
Hey,

You can remove log messages by setting NODE_ENV=production when compiling your script. 
In the next version I'll make it silent by default, and verbose only if explicitly specified. 

Cheers,

**Comment by RakanNimer** [comment]
New version on npm 1.0.2 is silent by default. To make it verbose set localStorage.debug to 'react-google-charts:*'. When you update make sure debug var in your browser's localStorage is set to ''.
