### ISSUE TITLE
Add hover event callback on chart (not data series)

### ISSUE THREAD

**Issue by stebogit** [rakannimer/react-google-charts#588]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

I noticed the google charts don't handle hovering events on the chat itself (only on the data series), so maybe it is not something you can/want to add, however it would be nice to have the option to interact with chart on hover and probably not hard to implement.
For example, by default [Highcharts](https://www.highcharts.com/demo/line-basic) shows the tooltip whenever the mouse hovers the chart. My specific interest is to show a vertical line (annotation or crosshair) to highlight the value of all the lines in my chart at any specific horizontal tick when the mouse hovers the chart, like in [this example](https://www.highcharts.com/demo/line-ajax) (I draw the mouse as an example):

![Screen Shot 2022-04-26 at 9 46 04 AM](https://user-images.githubusercontent.com/12717225/165351705-c7b4e7a0-5b74-4753-9f08-1d3053553333.png)

### Describe the solution you'd like

ideally when he mouse hovers over the chart an event is fired and you can provide the callback to be executed via `chartEvents` object.

**Comment by rakannimer** [comment]
You can use chartEvents with `eventName: "onmouseover"` to listen to mouseover and react to it.
