### ISSUE TITLE
Broken server render

### ISSUE THREAD

**Issue by BrunoQuaresma** [RakanNimer/react-google-charts#59]
When i import the react-google-chart the server rendering broken. 

`"Document is not defined"`

How can i use the module without this error?

**Comment by RakanNimer** [comment]
Unfortunately this is a [known issue](https://github.com/RakanNimer/react-google-charts#isomorphic-support). I will work on it when I have some time that frees up, meanwhile PRs are always appreciated if you think you can contribute a fix :)

**Comment by BrunoQuaresma** [comment]
Thanks @RakanNimer i will try do this.
