### ISSUE TITLE
Unable to load two charts at once

### ISSUE THREAD

**Issue by sbjovanovski** [RakanNimer/react-google-charts#60]
I'm trying to display two charts at once, Timeline and LineChart, whichever I put as a second chart (bellow the first one) I keep getting error for it "google.load is not a function". If I remove one of the charts, it's working perfectly. I checked the data, is correct. Cause when I'm loading them separately, they are working. Here's a sample of my code:

```
<FlexRow>
                <Chart chartType="Timeline"
                       graph_id="TimelineChart"
                       chartPackages={['timeline']}
                       rows={this.props.timeline.rows}
                       columns={this.props.timeline.columns}
                       width={"100%"} height={"400px"}/>
</FlexRow>
<FlexRow>
                <Chart chartType="LineChart"
                       rows={this.props.linechart.rows}
                       columns={this.props.linechart.columns}
                       width={"100%"} height={"400px"}/>
</FlexRow> 
```
What could be the problem?

**Comment by RakanNimer** [comment]
Hey,
Yeah this is a miscommunication in the api docs. For your timeline chart you need the timeline package and for the LineChart you need the corecharts which is loaded by default when no packages is specified in the props. But chartLoader is a singleton so it's only loading one (the one in the first chart you specify)

For now a fix would be to add 
``` chartPackages = {['timeline', 'corechart']} ````
for both. 
This will load them only once by the ChartLoader singleton so don't worry about extra bandwidth. 
Fixing this is next on my to do list, but for now this fix should do it :) 

Cheers !

**Comment by sbjovanovski** [comment]
Hey Rakan,
Thanks for the quick reply. Works perfect now :) 👍 . Looking forward to your new update/fix for it.

Cheers!
