### ISSUE TITLE
Turn off OnClick for chart legend

### ISSUE THREAD

**Issue by christchron** [RakanNimer/react-google-charts#61]
When i clicked the legend of my chart, it will turn off the line that i clicked. I want to know how to turn off that onclick function, because i edited the tooltip so the column is like:
{type:'datetime', label:'Date', role: 'domain'}, 
{type: 'number', label:'Chat Count', role: 'data'}, 
{type: 'string', role: 'tooltip', p: {'html': true}},
{type: 'number', label:'Chat Growth', role: 'data'},
{type: 'string', role: 'tooltip', p: {'html': true}}

when i clicked the legends, i got this error : All series on a given axis must be of the same data type

**Comment by RakanNimer** [comment]
Do you mean ```legend_toggle={false}``` ?

If not can you provide some code so that I can better see what you're trying to accomplish ?

**Comment by christchron** [comment]
I already tried the legend_toggle={false}, but it still working when i clicked the legend

here is the code i use:
<Chart chartType="LineChart"
         rows={rows} columns={columns}
         options={options}
         graph_id="LineChart"
         legend_toggle={false}
         width={"100%"}/>

**Comment by RakanNimer** [comment]
So with these props, clicking on the legend, hides the line or tells you "All
series on a given axis must be of the same data type"?

**Comment by christchron** [comment]
yes, that's why i want to turn off the legend toggle

**Comment by RakanNimer** [comment]
Did you try listening to the select event ?

**Comment by christchron** [comment]
Haven't tried it. How can i do that?

**Comment by RakanNimer** [comment]
Check [here](https://github.com/RakanNimer/react-google-charts#listen-to-chart-events). And replace onmouseover with select.
