### ISSUE TITLE
[Bug]: Not getting selected iterate node on react_google_charts Treemap

### ISSUE THREAD

**Issue by ashishk116** [rakannimer/react-google-charts#613]
### Would you like to work on a fix?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Hi ,I am using react_google_charts Treemap in the project component . But not getting the selected iterated node from the package .

Issue reproduce-->  https://user-images.githubusercontent.com/50401674/170448907-c8c6d7b9-ddec-4a63-a41f-a7211d0d7b3a.mp4

Uncaught Error: Invalid row index 84. Should be in the range [0-4].Getting this error while trying to get the node of iterated graph node. 
Codesandbox link - https://codesandbox.io/s/tender-chebyshev-xyg6cx

Please suggestion on this issue would be very helpful.

 

### Reproduction

https://codesandbox.io/s/tender-chebyshev-xyg6cx

### react-google-charts version

^4.0.0

**Comment by rakannimer** [comment]
Your example works with latest react-google-charts > 4
