### ISSUE TITLE
Fetching Data via Data Source

### ISSUE THREAD

**Issue by awitherow** [RakanNimer/react-google-charts#63]
Currently we fetch our data from Google Spreadsheets in a project I am working on. If I were to fetch this data and then pass it to the component, would it be able to accept the response?

I'm not 100% sure how I would go about doing the google.visualization calls.

```new google.visualization.Query```

perhaps we could pass in a query prop and we could create a function within react-google-charts that would do the fetching and setting of data?

**Comment by awitherow** [comment]
@RakanNimer you got any ideas on this?

**Comment by RakanNimer** [comment]
It depends on what the data returned from Google Spreadsheets looks like. 
You might need to format it before feeding it into the component. Please read the documentation to see the different ways to pass data to it. 

Regarding your idea of passing a query prop, PRs are welcome if you'd like to work on this.

Cheers.
