### ISSUE TITLE
warning message when there is no data

### ISSUE THREAD

**Issue by degr** [RakanNimer/react-google-charts#64]
Chart with this properties show error message
>Data column(s) for axis #0 cannot be of type string

{"chartType":"BarChart","data":[["Element","Density",{"role":"style"}]],"width":"100%","height":"300px","options":{"title":"Density of Precious Metals, in g/cm^3","bar":{"groupWidth":"95%"},"legend":{"position":"none"}},"chartEvents":[{"eventName":"onmouseover"}]}

**Comment by RakanNimer** [comment]
Please check examples and README. and edit for your code accordingly

**Comment by degr** [comment]
This is not my code, this is YOUR code, and it available here, just remove data from properties - http://rakannimer.github.io/react-google-charts/#/examples/BarChart?_k=hyfwe6
In 99% cases chart will have no data initially, it will be loaded asyncronously.

**Comment by RyanThomasMusser** [comment]
I know I'm two years late to this thread... @degr did you ever solve for this? I'd really like to not show that error message while loading with no data...

**Comment by degr** [comment]
no
