### ISSUE TITLE
Options are not documented

### ISSUE THREAD

**Issue by LuckyBumblebeeHive** [rakannimer/react-google-charts#652]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

I want to see the full set of options that can be passed to the <Chart/> component.
I was able to figure out a few things by trial and error but that's not how this is supposed to go.
For example, how can I hide the helper horizontal lines ? Or change the color for a data set? Change the gradient for area ?

### Describe the solution you'd like

Documentation

### Describe alternatives you've considered

Trial and error.

**Comment by rakannimer** [comment]
That's a fair callout, maybe I can add a link to each chart type to the full list of configuration options in google charts. 

Example for pie chart: https://developers.google.com/chart/interactive/docs/gallery/piechart#Configuration_Options
