### ISSUE TITLE
How to invoke getImageURI method on chart

### ISSUE THREAD

**Issue by azakordonets** [RakanNimer/react-google-charts#66]
Hi, i'm trying to save chart that i'm building with your component into pdf. For that, i need to get dataUri of the chart, but i can't figure out how to do it. From official docs i see that [it's possible to call on chart object](https://developers.google.com/chart/interactive/docs/printing), but how can i retrieve this object from react component ?

**Comment by RakanNimer** [comment]
Hey, the chart is stored as a property of the component, I haven't added a getter for it.  You can grab it using the component ref for now.

Hope that helps.

**Comment by azakordonets** [comment]
Could you give me an example ? I'm a newby to react world :)

**Comment by RakanNimer** [comment]
Sure, this gist should do it : https://gist.github.com/RakanNimer/327a347411253806e5530544c3a4f7f5

**Comment by azakordonets** [comment]
Thanks a lot for helping me , but i still have very weird behaviour. My component looks like this : 
```javascript
import React  from 'react';
import {render} from 'react-dom'
import {Chart} from 'react-google-charts'
class ExtremeIssuesTrendChart extends React.Component {

  componentDidMount = () => {
    console.log('Props in trend chart are', this.props);
    console.log('Chart  ', this.GoogleChart);
    const googleChart = this.GoogleChart;
    for (let prop in googleChart) {
      if (googleChart.hasOwnProperty(prop)){
        console.log('Prop is', prop, 'And value is ', googleChart[prop]);
      }
    }
    console.log('Chart data is ', this.GoogleChart['chart']);
    this.props.setChartUri(this.GoogleChart.chart.getImageURI())
  };

  render() {
    const options = {
      title : 'Extreme Issues trend',
      vAxis: {title: 'Amount'},
      hAxis: {title: 'Fix Version'},
      seriesType: 'bars'};
      const data = [];
    data.push(['FixVersion', 'Bug', 'Total', 'Other']);
    this.props.stories.map(fixVersionDetails => {
      const detailsArray = [];
      detailsArray.push(fixVersionDetails.fixVersion);
      detailsArray.push(fixVersionDetails.bug);
      detailsArray.push(fixVersionDetails.total);
      detailsArray.push(fixVersionDetails.other);
      data.push(detailsArray);
    });

    return (
    <div id='extremeIssuesTrendChart' style={{"zIndex": 2}}>
      <Chart ref={(ref) => this.GoogleChart = ref}
             chartType = "ComboChart"
             data = {data}
             options = {options}
             graph_id = "ScatterChart"
             width={"100%"}
             height={"400px"}
             legend_toggle={true}
      />
    </div>
    );
  }
}

export default ExtremeIssuesTrendChart;
```
In console i see next output : 
```javascript
Chart   Chart {props: Object, context: Object, refs: Object, updater: Object, state: Object…}
Prop is props And value is  Object {chartType: "ComboChart", data: Array[9], options: Object, graph_id: "ScatterChart", width: "100%"…}
Prop is context And value is  Object {}
Prop is refs And value is  Object {}
Prop is updater And value is  Object {}
Prop is state And value is  Object {graphID: "ScatterChart"}
Prop is chart And value is  null
Prop is wrapper And value is  null
Prop is hidden_columns And value is  Object {}
Prop is dataTable And value is  []
Prop is _reactInternalInstance And value is  ReactCompositeComponentWrapper {_currentElement: Object, _rootNodeID: 0, _compositeType: 0, _instance: Chart, _hostParent: ReactDOMComponent…}
Chart data is  null
Uncaught TypeError: Cannot read property 'getImageURI' of null
```

But when i look into the GoogleChart object in developer tools, i see that chart has properties ( How is this possible ???? ) 
![Chart object screenshot](https://www.dropbox.com/s/w589q8hb7qpvo2r/Screenshot%202016-09-02%2009.45.47.png?dl=0)

**Comment by RakanNimer** [comment]
You have to wait until the chart is initialised before accessing it. You're trying to access the chart on componentDidMount but the chart is not ready yet. Since it's the same object, it's being logged correctly after the chart is ready. 

I will try to add an onReady prop to the component later this week. Meanwhile if you want a temporary *ugly hack* use a setTimeout before grabbing the Chart.

**Comment by azakordonets** [comment]
Thanks, that worked :) Had to add 500 ms timeout and it worked for me. Could you comment on this issue when you add onReady prop ? Then we would close this issue. 

Thanks again for such a quick response and help.

**Comment by RakanNimer** [comment]
Happy to help :)

Turns out there's no need to change the code, you can just listen to the ready event from google charts. I updated the gist accordingly : 
https://gist.github.com/RakanNimer/327a347411253806e5530544c3a4f7f5

Cheers.

**Comment by azakordonets** [comment]
Hi, thanks for the tip. I'm having some troubles with this code. I've added chart_events into componentDidMount and added ```this.setState({'chart_events: chart_events})``` , but in render method i get ```null``` for this.state. Therefore my component fails when i try to specify it as : 
```javascript
<div id='extremeIssuesTrendChart' style={{"zIndex": 2}}>
      <Chart ref={(ref) => this.GoogleChart = ref}
             chartType = "ComboChart"
             data = {data}
             options = {options}
             graph_id = "ScatterChart"
             width={"100%"}
             height={"400px"}
             legend_toggle={true}
             chartEvents = {this.state.chart_events}
      />
    </div>
```

**Comment by azakordonets** [comment]
Actually, i just found a solution for this :) I just added : 

```javascript 
constructor() {
    super();
    this.state = {'chart_events': undefined};
  }
```

Thanks a lot for your help :)
