### ISSUE TITLE
[Bug]: No Material UI Support?

### ISSUE THREAD

**Issue by machineghost** [rakannimer/react-google-charts#670]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

The only reference I could find on making a Material UI chart was in this orphaned file: https://github.com/rakannimer/react-google-charts/blob/46152f0c1b898ca9f51f29567d377bb7f10430f6/website/docs/examples/line.mdx.

There should be a working example of a Material chart (ideally for every chart type that supports Material).

### Reproduction

https://github.com/rakannimer/react-google-charts

### react-google-charts version

Latest

### Possible solution

Add examples (and code to support Material UI, if the library doesn't already).

**Comment by rakannimer** [comment]
Added 
- Bar Chart Material Design https://www.react-google-charts.com/examples/bar-chart-material
- Line Chart Material Design https://www.react-google-charts.com/examples/line-chart-material
