### ISSUE TITLE
Support custom style for default " Rendering Chart... " tip

### ISSUE THREAD

**Issue by neekey** [RakanNimer/react-google-charts#69]
By default, the chart will show a raw `Rendering Chart...` string, it's quite styleless. Can you add a custom style option for the style? or just make it look better?

![image](https://cloud.githubusercontent.com/assets/499870/18698264/1c687474-800c-11e6-8213-f88b5a1c7b2f.png)

**Comment by RakanNimer** [comment]
Yeah, I agree with you. This pull request addresses this : https://github.com/RakanNimer/react-google-charts/pull/68

I'll merge it later this week and add this option ! Will notify you here when I release it

**Comment by RakanNimer** [comment]
Fixed in latest release, you can use loader props to give it anything to render.

**Comment by neekey** [comment]
@RakanNimer It works, Thanks 👍
