### ISSUE TITLE
[Bug]: Geo chart (maybe other) doesn't respect React@18 StrictMode

### ISSUE THREAD

**Issue by newsiberian** [rakannimer/react-google-charts#699]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

select event doesn't call when Chart covered in a StrictMode

### Reproduction

https://codesandbox.io/s/bold-fire-4x46vb?file=/App.tsx

### react-google-charts version

4.0.0

**Comment by rakannimer** [comment]
Fixed in version >= 5

Related to 708
