### ISSUE TITLE
IE9 compatibility

### ISSUE THREAD

**Issue by MouradMessiha** [rakannimer/react-google-charts#70]
In IE9 the charts display a message like 'Invalid chart type: LineChart' and the console displays: SCRIPT5009:  'gvjs_lk' is undefined

The same code works fine in Chrome.

**Comment by RakanNimer** [comment]
I don't plan on adding ie9 compatibility, but happy to accept a PR for it !

**Comment by hozefaj** [comment]
Other than IE11 and Edge, it does not make sense to support any other IE versions.
