### ISSUE TITLE
[Bug]: Select event is not working in strict mode.

### ISSUE THREAD

**Issue by harichandu1** [rakannimer/react-google-charts#708]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

<Chart
      chartEvents={[
        {
          eventName: "select",
          callback: ({ chartWrapper }) => {
            console.log('-------- console is not getting printed-')
            const chart = chartWrapper.getChart();
   
          },
        },
      ]}
      chartType="GeoChart"
      width="100%"
      height="100vh"
      data={data}
/>

### Reproduction

https://codesandbox.io/s/bold-fire-4x46vb?file=/App.tsx

### react-google-charts version

v4.0.0

**Comment by dorlanpabon** [comment]
Post a pull request for solve this problem https://github.com/rakannimer/react-google-charts/pull/709

**Comment by rakannimer** [comment]
Thanks @dorlanpabon, 

Confirmed this is fixed in the sandbox above by just updating the version to latest (5)
