### ISSUE TITLE
[Bug]: Charts with spreadsheets does not work

### ISSUE THREAD

**Issue by JoaoVSBraz** [rakannimer/react-google-charts#712]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Currently the charts examples using data from a google spreadsheet doesn't work propertly. The error message "Table has no column" is returned. The expected behavior is to view a google chart rendered.

### Reproduction

https://codesandbox.io/s/github/RakanNimer/react-google-charts/tree/master/sandboxes/advanced-spreadsheet/default?from-embed=&file=/App.tsx

### react-google-charts version

4.0.0

**Comment by ukneeq** [comment]
I am experiencing this issue as well. I see this was added as a bug last year. Anyone look at this yet?

**Comment by rakannimer** [comment]
The sandbox you linked to now loads correctly.

https://codesandbox.io/s/github/RakanNimer/react-google-charts/tree/master/sandboxes/advanced-spreadsheet/default?from-embed=&file=/App.tsx

<img width="1114" alt="Screenshot 2024-09-26 at 7 09 34 PM" src="https://github.com/user-attachments/assets/c93dd870-384b-4f47-912f-9bbd82218a80">
