### ISSUE TITLE
[Bug]: Incorrect Bar chart in react-google-charts

### ISSUE THREAD

**Issue by vah13** [rakannimer/react-google-charts#718]
### Would you like to work on a fix?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

When drawing a bar chart, in some cases, it's drawing incorrect 

![image](https://github.com/rakannimer/react-google-charts/assets/7976421/6359175d-c743-4fc9-b46f-de147daeace3)

### Reproduction

https://codesandbox.io/p/sandbox/google-bar-ui-bug-233sn5?file=%2FApp.tsx%3A18%2C23

### react-google-charts version

4.0.1

**Comment by YamatoDX** [comment]
Try putting the values as numbers not strings. See if it solves the problem.

**Comment by YamatoDX** [comment]
![image](https://github.com/rakannimer/react-google-charts/assets/78369801/6fa58ebc-a0a9-4df9-b8b0-72d26d93df10)
See problem solved ? @vah13

**Comment by rakannimer** [comment]
Thanks @YamatoDX. Resolving.
