### ISSUE TITLE
[Bug]: this.Ay.xq is not a function

### ISSUE THREAD

**Issue by Konlll** [rakannimer/react-google-charts#719]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I have this chart which looks pretty good:
![kép](https://github.com/rakannimer/react-google-charts/assets/24209014/63d744a2-9cae-44f6-ae33-05b421cb6842)

But if I navigate to another page and refresh it, and I navigate back to the original page, I get this error:
![kép](https://github.com/rakannimer/react-google-charts/assets/24209014/8895b867-5096-4089-8fdc-6b1beeccdfc6)

![kép](https://github.com/rakannimer/react-google-charts/assets/24209014/d1a3b155-bb1c-4a2d-a39e-c92d8e0ecee3)
Every variables has the correct value even if this error shows up.

Any ideas?

### Reproduction

This is a private project, I'm not allowed to link any repo.

### react-google-charts version

4.0.1

**Comment by rakannimer** [comment]
It's very hard to find the issue based on the information you provided. Could you try creating a minimal reproduction of the issue on code sandbox and sharing it here so we can help you debug further.

Thanks ! Please re-open once you have it.
