### ISSUE TITLE
NumberFormat

### ISSUE THREAD

**Issue by koppert** [RakanNimer/react-google-charts#72]
Hi,

Is there any way to apply google.visualization.NumberFormat?

https://developers.google.com/chart/interactive/docs/reference#numberformat

**Comment by Nevraeka** [comment]
I am running into the same issues

**Comment by Nevraeka** [comment]
@RakanNimer I tried to wrap this with a formatter with no luck. I am happy to pair on this or submit a PR since I need this for a project releasing soon. What code would need to be adjusted to make this happen?

**Comment by koppert** [comment]
I think we could transfer NumberFormat config ({prefix: '$', negativeColor: 'red', negativeParens: true}) via props and execute formatter.format on buildDataTableFromProps. 
I will try.

**Comment by koppert** [comment]
I made the change, but I can not compile.

```shell
$ npm run build

> react-google-charts@1.2.1 build C:\Users\bruno.barros\Desktop\Apps\react-google-charts
> nwb build

nwb: clean-module
nwb: build-module (es5)
ReferenceError: [BABEL] C:\Users\bruno.barros\Desktop\Apps\react-google-charts\src\components\Chart.js: Unknown option: C:\Users\bruno.barros\Desktop\Apps\react-google-charts\.babelrc.presets
```

**Comment by RakanNimer** [comment]
Hey !
Thanks for using the library and reporting this. 

@koppert, could you try to install nwb. 
```
npm install -g nwb
```
and then build with it: 
```
nwb build
```

I'm very happy to accept a PR for this. And will try to do it in the weekend if no PR is submitted. 

So @Nevraeka you should be covered for your upcoming release. 

Thanks @koppert for digging in the code, if you still get build errors submit a PR with some example code that you'd like to work and I'll try it on my machine.

Cheers !

**Comment by Nevraeka** [comment]
Many Thanks @RakanNimer & @koppert . This should cover percentage decimal formatting as well, correct?

**Comment by koppert** [comment]
@RakanNimer It works. Just do not compiled the demo, but no problem. Thanks.

@Nevraeka Correct. That's right. All options available in NumberFormat.

I have not had time to test. But the changes are these:

https://github.com/koppert/react-google-charts/commit/5c15e7c522a2c9ff91608ac7d1b4eacf701ebf7c

**Comment by RakanNimer** [comment]
Thanks @koppert I integrated your code change. Can one of you guys try out the master branch and let me know if it works for your use case ?
Cheers !

**Comment by claudiowilson** [comment]
@RakanNimer @koppert wouldn't this change only allow for 1 column to be formatted?

**Comment by koppert** [comment]
I would like to apologize for my absence.

NumberFormat would not solve my problem. I wanted to format vaxis in a column chart. Only then I realized that it should be used in table chart.

@claudiowilson You're right. I will modify the code to pass an array in the props.

**Comment by darioodiaz** [comment]
Hi guys ! Did you make the PR? because in the code this feature is missing

**Comment by aikonplus** [comment]
As far as I can see, it is still not possible to format more than one column at once. Any chance this will attract any attention?

**Comment by nslocum** [comment]
@aikonplus #167

**Comment by aikonplus** [comment]
There seems to be an issue. When trying to use formatters I get this error:

`TypeError: _this4.applyNumberFormat is not a function
`
Seems the issue is somewhere here: 

```
this.props.formatters.forEach(({ type, column, options }) => {
      switch (type) {
        case 'NumberFormat':
          this.applyNumberFormat(column, options);
        case 'DateFormat':
          this.applyDateFormat(column, options);
        default:
          console.log('Unkown formatter type: ' + type);
          break;
      }
    });
```

**Comment by Michto8** [comment]
Hello aikonplus ,I have the same error. 
I solved by mooving the 2 scoped functions applyNumberFormat and applyDateFormat into class Chart method (for matching 'this' in the context of the call).

I have also add some `break;` into the swith case and now it s seem to work correctly.
Cordially.
