### ISSUE TITLE
Chart.defaultProps.height/width shadows options.height/width

### ISSUE THREAD

**Issue by dkwingsmt** [rakannimer/react-google-charts#75]
This is the code to compute the div style at https://github.com/RakanNimer/react-google-charts/blob/master/src/components/Chart.js#L273

```
    const divStyle = {
      height: this.props.height || this.props.options.height,
      width: this.props.width || this.props.options.width,
    };
```

I assume its purpose is "when `this.props.height` is absent, fallback to `this.props.options.height`".

But then we have `defaultProps` from https://github.com/RakanNimer/react-google-charts/blob/master/src/components/Chart.js#L324 which says

```
Chart.defaultProps = {
  width: '400px',
  height: '300px',
};
```

which provides `this.props.height` already when it's absent, and that `||` will never take effect unless `this.props.height` is manually set to `null` of `0` etc, and leaving `height` to be always 300px if we set `options.height` to some value without setting `props.height`, making the behaviour very confusing

**Comment by RakanNimer** [comment]
Hey ! 
Very good point thanks for bringing that up ! 
Having two ways to set width and height is not a good idea anyway, We need to find a way to set it from one place only without breaking backwards compatibility. 

Do you feel like doing a PR for this ?

If not I'll get to it later this week and report back here :)

Cheers !

**Comment by dkwingsmt** [comment]
I'd really love to, however since I've only started using this library recently (like a few days),  I probably can not fully understand what is the best interface for it. I guess it's best to leave it to the author atm :)

Thank you for your response!
