### ISSUE TITLE
enabling diff charts

### ISSUE THREAD

**Issue by HenrikBechmann** [RakanNimer/react-google-charts#76]
Grist for the mill: I've enabled diff charts by adding the following code to buildDataTableFromProps:

```
  buildDataTableFromProps() {
    // debug('buildDataTableFromProps', this.props);
    if (this.props.diffdata) {

        let diffdata = this.props.diffdata
        let oldData = google.visualization.arrayToDataTable(diffdata.old)
        let newData = google.visualization.arrayToDataTable(diffdata.new)
        // must take computeDiff from prototypes since not available with charts early in process
        let computeDiff = google.visualization[this.props.chartType].prototype.computeDiff
        let chartDiff = computeDiff(oldData,newData)

        return chartDiff

    }

```
(and of course adding a diffdata prop)

The key is getting access to the `computeDiff` method before having access to the chart for the chartType. Grabbing it from the appropriate prototype in the google.visualization access chain seems to work.

**Comment by RakanNimer** [comment]
Hey ! 
Thanks for that ! 
Could you also give me the shape of the diffdata object so I can integrate this and add to tests ?

**Comment by RakanNimer** [comment]
Could you give master branch a try and let me know if it 's working for you. I fixed event clearing and added diff support. Will publish once I get confirmation :) 

Thanks !

**Comment by HenrikBechmann** [comment]
```
diffdata = null // to skip

diffdata = {
   old:old_dataarray, // like data
   new:new_dataarray, // like data
}

```

works for piechart, columnchart, and (I believe) scatterchart (haven't tried the latter)

I'm really stretched, but can perhaps try next week

Glad you like it!
