### ISSUE TITLE
[Bug]: Org Chart root node ignores the formatted value

### ISSUE THREAD

**Issue by swandrn** [rakannimer/react-google-charts#769]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

This bug is even present in the Org Chart example of the [official website](https://www.react-google-charts.com/examples/org-chart).
```
export const data = [
  [
    {
      v: "Mike",
      f: 'Mike<div style="color:red; font-style:italic">President</div>',
    },
    "",
    "The President",
  ],
  [
    {
      v: "Jim",
      f: 'Jim<div style="color:red; font-style:italic">Vice President</div>',
    },
    "Mike",
    "VP",
  ],
  ["Alice", "Mike", ""],
  ["Bob", "Jim", "Bob Sponge"],
  ["Carol", "Bob", ""],
];
``` 
This code gives the following result 
![image](https://github.com/user-attachments/assets/bb88948a-0285-4af5-8dfb-6654cdc0887a)
Where the formatted value `f: 'Mike<div style="color:red; font-style:italic">President</div>',` is completely ignored.

All other nodes behave as expected.

### Reproduction

https://www.react-google-charts.com/examples/org-chart

### react-google-charts version

5.1.0

**Comment by rakannimer** [comment]
Hey @swandrn,

Thanks for reporting this, the problem in the example is that the columns row is missing, I updated the example and now the formatted value appears even in the first item of the org chart.

Please try this and see if it fixes it for you. Feel free to re-open the ticket if it doesn't !

Example https://github.com/rakannimer/react-google-charts/commit/d791494fdecd7d96950910aa1177d82fac95ec09
