### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by JrmKrb** [rakannimer/react-google-charts#79]
Hi,

It seems that we can use different locale (mainly to translate the dates) with GoogleChart but I didn't find a way to do it with react-google-charts.

I tried to change the library myself to include another language when loading the GoogleChart library but it didn't work.

is it possible to change the locale of the library or to make it a parameter of the component?

Thanks for your help,
Jeremy

**Comment by jfernandogt** [comment]
Hello,

Do you have news about this?

I can try implement it.

regards,

**Comment by RakanNimer** [comment]
Hey @jfernandogt, 

I've been pretty busy lately so didn't have time to do it yet. 

Would love it if you take a shot at it. 

Let me know if I can help.
Cheers !

**Comment by DmitryMaksakov** [comment]
Hello,

@jfernandogt, @RakanNimer is anyone solving the problem at the moment?

Regards,
Dmitry

**Comment by RakanNimer** [comment]
@DmitryMaksakov Nope, I'll update here when I start, would you like to take a shot at it ?

**Comment by Riepsma** [comment]
Hello, 

Is there an update on this already?

Regards,
Robert

**Comment by JrmKrb** [comment]
Solved by #79
