### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by nairufan** [RakanNimer/react-google-charts#80]
Can not use chart offline?

**Comment by RakanNimer** [comment]
Yeah can't use offline for now unfortunately :( . It needs to download google charts libraries from Google servers. Using it offline is against the ToS. Check this issue for context : https://github.com/google/google-visualization-issues/issues/277

**Comment by nairufan** [comment]
Got it. Thanks for your patient reply.

**Comment by sharifiniaa** [comment]
@rakannimer Is there any update ?

**Comment by 51yu** [comment]
If encounter network connectivity problem, should we display explicit error message and ask user to reload instead of show nothing ... ? user may have no idea what's going on @rakannimer
