### ISSUE TITLE
Error to run the Demo Development Server

### ISSUE THREAD

**Issue by jfernandogt** [rakannimer/react-google-charts#81]
I have this error:
![image](https://cloud.githubusercontent.com/assets/7839474/20190282/5d2deb36-a746-11e6-9a98-caefc610a428.png)

I tried to update the packages and other solutions...

**Comment by hozefaj** [comment]
Make sure you have `babel-preset-es2015` and `babel-preset-react` installed inside your `node_modules`.

In most this might be an issue with version of the `modules. Also you can nuke `node_modules`, clear `npm` cache and `npm install`.

**Comment by rakannimer** [comment]
I updated the build and dev tools, this is definitely fixed on master :) 

Cheers !
