### ISSUE TITLE
Multiple Charts on one page

### ISSUE THREAD

**Issue by chrish-21** [RakanNimer/react-google-charts#84]
It appears that it's not possible to render multiple charts on the same page.

When i import the example chart and want to show it twice:
```
<ExampleChart />
<ExampleChart />
```

It only shows the first chart and the second one gets stuck on rendering chart. Google has a guide about how to render multiple charts on the same page (https://developers.google.com/chart/interactive/docs/basic_multiple_charts). I'm not sure how you would implement that here so

**Comment by RakanNimer** [comment]
Hello, which version of the library are you using ? 
This is a problem that should have been solved many versions ago.

**Comment by chrish-21** [comment]
Hi, I am using version 1.2.1.

I just created a new test project using create-react-app and only installed react-google-charts.

Then I created ExampleChart.js with the example code:
```
import {Chart} from 'react-google-charts';
import React from 'react'

class ExampleChart extends React.Component {
  constructor(props){
    super(props);
    this.state={
      options:{
            title: 'Age vs. Weight comparison',
          hAxis: {title: 'Age', minValue: 0, maxValue: 15},
          vAxis: {title: 'Weight', minValue: 0, maxValue: 15},
          legend: 'none'
      },
      data:[
            ['Age', 'Weight'],
            [ 8,      12],
            [ 4,      5.5],
            [ 11,     14],
            [ 4,      5],
            [ 3,      3.5],
            [ 6.5,    7]
      ]
    };
  }
  render() {
    return (
      <Chart
        chartType="ScatterChart"
        data={this.state.data}
        options={this.state.options}
        graph_id="ScatterChart"
        width="100%"
        height="400px"
        legend_toggle
       />
    );
  }
};
export default ExampleChart;
```

And changed App.js to:

```
import React, { Component } from 'react';
import ExampleChart from './ExampleChart.js';

class App extends Component {
  render() {
    return (
      <div>
        <ExampleChart/>
        <ExampleChart/>
        <ExampleChart/>
      </div>
    );
  }
}

export default App;
```
And it is only rendering one chart:

![chart-not-rendering](https://cloud.githubusercontent.com/assets/22555626/20797274/5a43c3ce-b7da-11e6-8b11-45fac4fea980.png)

**Comment by RakanNimer** [comment]
Oh ok I see what the problem is. You're assigning the same graph_id prop to
all three. You can either pass a custom one for each graph or don't give it
the prop and it will generate a unique id for each one.

**Comment by chrish-21** [comment]
Perfect, that fixed it. Thank you!
