### ISSUE TITLE
Chart does not work on mobiles

### ISSUE THREAD

**Issue by openedhardware** [rakannimer/react-google-charts#85]
Hi.

I have been using your great chart package on my web app successfully.
By the way, it does not work on mobile.

It says "Rendering Chart", and does not display anything.

Would you like to check on mobile?

**Comment by RakanNimer** [comment]
Yep sure, can you give me more information ? Which mobile OS and browser ?

**Comment by openedhardware** [comment]
Thanks for your quick reply
Would you mind to check my web app?

https://biowall.apps.exosite.io
username: a@a.com
password: 12345678

Please select "Wester" and press any sensor(Temperature or Pressure).
You could see a chart and a table.

But if I try it with my iPhone(safari), it does not show chart...

Best.
