### ISSUE TITLE
Using React components in Table chart

### ISSUE THREAD

**Issue by eltongonc** [rakannimer/react-google-charts#88]
Hi, 

I was wondering if there is a way to use a <Link> tag  from react-router in the Table component. Right now i have `const tableData2 =[
          ['Title', 'Status'   , ' ' ],
          ['Document 1', 'in progress', `<a class="btn btn-primary" href='link'>Open</a>`]
        ]`
this works, but its not "the react-router way".

Is there a way to making it work like this: `const tableData2 =[
          ['Title', 'Status'   , ' ' ],
          ['Document 1', 'in progress', `<Link class="btn btn-primary" to='link'>Open</Link>`]
        ]`

Thank you in advance

**Comment by RakanNimer** [comment]
Hmm, haven't tried to do something similar with it yet. Will leave this open if someone reads this and can helo :)

Cheers !
