### ISSUE TITLE
ToolBar feature does not work

### ISSUE THREAD

**Issue by jzkunlun** [rakannimer/react-google-charts#90]
I want to export chart or data table with ToolBar from google chart. I could not find its implementation.

**Comment by RakanNimer** [comment]
Indeed it's not implemented. Happy to accept a PR for it !

**Comment by rakannimer** [comment]
Done ! 

You can use Toolbars starting at version `3.0.1`

[Demo](https://react-google-charts.com/google-charts-toolbar)
