### ISSUE TITLE
Organization Chart?

### ISSUE THREAD

**Issue by rickyhan** [rakannimer/react-google-charts#92]
Is it possible to integrate this chart in the future? 

https://developers.google.com/chart/interactive/docs/gallery/orgchart

**Comment by RakanNimer** [comment]
It should be feasible, could you try passing ['corechart', 'orgchart'] to [chartPackages prop](https://github.com/RakanNimer/react-google-charts/blob/master/docs/Chart.md#chartpackages).

Then you should be able to draw it like any other chart .

**Comment by rakannimer** [comment]
Here's an example OrgChart [CodeSandbox](https://codesandbox.io/s/q3pxx760n9).

Try it out :)
