### ISSUE TITLE
Bluebird, is it necessary?

### ISSUE THREAD

**Issue by dvdplm** [RakanNimer/react-google-charts#95]
It would be absolutely lovely to be able to opt-in to bluebird, so that projects targeting modern browsers can use the native promises implementation and shed some weight. Is that anything you'd be interested in? A quick glance at the code seem to suggest promises are not used extensively.

**Comment by RakanNimer** [comment]
Hello,
Yeah that would be great ! bluebird is only used in ChartLoader so should be straight-forward to do. 
Happy to accept PRs.
