### ISSUE TITLE
Invalid JSON string

### ISSUE THREAD

**Issue by rgstephens** [rakannimer/react-google-charts#96]
I'm using the Quick Start example data but getting an Invalid JSON string error:

```
Invalid JSON string: {"vAxes":[{},{}],"hAxis":{}}
```

I think this may have something to do with how the JSON is generated in the Meteor build environment.

**Comment by RakanNimer** [comment]
Hmm. Could you try the exact code from example/App.js ?

**Comment by muhammeta7** [comment]
I am having the same exact issue even after I tried the exact code from App.js

**Comment by t47io** [comment]
I ran into this issue to. In my case, I had a CSP rule with `script-src 'self' 'unsafe-inline' ...`. It turned out that the google-charts lib is using `eval()` internally. So adding `'unsafe-eval'` to your CSP header would help.
