### ISSUE TITLE
Gaps on line charts

### ISSUE THREAD

**Issue by SammyIsra** [RakanNimer/react-google-charts#97]
I am having an issue with line graphs. For some reason, I am getting gaps between lines and points in the line graph, like this:

http://i.imgur.com/WFEUgr0.png

I understand that this may be caused by gaps in data table. Is there a way to just still have a connection between the lines even if there connection is fragmented?

**Comment by RakanNimer** [comment]
Yeah, you can change the chart type and it should render lines. Try LineChart ? If it doesn't work please post some code I can run to help you debug

**Comment by SammyIsra** [comment]
This is what I have on the module call
```
<Chart
    chartType="LineChart"
    data={this.state.chartData}
    options={this.state.options}
    graph_id="ScatterChart"
    width={"100%"}
    height={"800px"}
    legend_toggle={true} />
```

Here are my options, if necessary
```
var options = {
    title: "Mood Analysis Of The Top 500 posts of r/NoMansSkyTheGame. Average per month.",                colors: ['red', 'green', 'orange', 'yellow', 'blue'],
    legend: {
        position: 'right'
    },
    hAxis: {
        title: 'Month',
        gridlines: {
            count: -1
        }
    },
    vAxis: {
        title: 'Mood',
        gridlines: {
            count: -1
        }
    }
}
```

**Comment by RakanNimer** [comment]
Are your data points in this.state.chartData sorted by Date (x-axis) ? Could you try that ?

**Comment by RakanNimer** [comment]
Any update ?

**Comment by SammyIsra** [comment]
Sorry, yes there;s an update. The reason why there were gaps was because
the dataset dates were not continuous, and the graph would not make the
jump in some of the gaps. My workaround was grouping the data by month
instead.

**Comment by RakanNimer** [comment]
Great ! Thanks for reporting back :) 

Closing issue.
